services:
  backend:
    build:
      context: ya_music/
    container_name: ya_music_service_1
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    env_file:
      - ya_music/.env
    restart: no

  db:
    image: postgres
    env_file:
      - ya_music/.env
    environment:
      POSTGRES_PASSWORD: "hackme"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    # command: ["-c", "log_min_messages=debug"]
    ports:
      - 5432:5432
    volumes:
      - /home/grivvus/docker_volumes/postgres/ya_music:/var/lib/postgresql/data/
    restart: no

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "hackme123"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data


volumes:
  minio_data:
    driver: local
    driver_opts:
      type: none
      device: /home/grivvus/docker_volumes/minio
      o: bind
