services:

  service:
    depends_on:
      db:
        condition: service_healthy
      storage:
        condition: service_healthy
      init-minio:
        condition: service_completed_successfully
    build:
      context: .
    volumes:
      - ./.env.minio:/.env.minio:rw
    develop:
      watch:
        - action: rebuild
          path: .
          include: "*.go"
    ports:
      - 8000:8000
    restart: "no"

  db:
    image: postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 5432:5432
    restart: no
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.goose
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  storage:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    command: server /data --console-address ":9001"
    restart: no
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 5s
      retries: 12
      start_period: 5s
      timeout: 3s

  init-minio:
    build:
      context: .
      dockerfile: Dockerfile.minio.init
    depends_on:
      storage:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./init-minio.sh:/workdir/init-minio.sh:ro
      - ./:/workdir/
    restart: "no"

volumes:
  minio_data:
    driver: local
    driver_opts:
      type: none
      device: /home/grivvus/docker_volumes/minio
      o: bind
  postgres_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/grivvus/docker_volumes/postgres/ym
      o: bind
