apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  type: NodePort
  selector:
    app: ym-pg
  ports:
    - protocol: TCP
      name: db-access
      port: 5432
      targetPort: 5432
      nodePort: 30432
