# example values
apiVersion: v1
kind: Secret
metadata: 
  name: ym-secret

type: Opaque
stringData:
  JWT_SECRET: secret
  POSTGRES_PASSWORD: hackme
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres

  S3_ROOT_USER: minio
  S3_ROOT_PASSWORD: hackme123
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: hackme123
  MINIO_ACCESS_KEY: 0GDHGKZZLBCC9N72GA89
  MINIO_SECRET_KEY: OV+CZz4S++QXN6Di1Y4+LuyEKg7EuOpPqHv7mb6C

  PASSWORD_RESET_ENABLED: "false"
  PASSWORD_RESET_CODE_SECRET: ""
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  SMTP_FROM_ADDRESS: ""
  SMTP_FROM_NAME: YM
  SMTP_TLS_MODE: starttls

  GOOSE_DRIVER: postgres
  GOOSE_DBSTRING: postgres://postgres:hackme@pg-headless:5432/postgres
