apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
spec:
  type: NodePort
  selector:
    app: ym
  ports:
    - protocol: TCP
      name: nodeport-api
      port: 8000
      targetPort: 8000
      nodePort: 30800
