// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ExtendedPlaylistPlaylistType.
const (
	Owned  ExtendedPlaylistPlaylistType = "owned"
	Public ExtendedPlaylistPlaylistType = "public"
	Shared ExtendedPlaylistPlaylistType = "shared"
)

// Defines values for OperationStatus.
const (
	Error    OperationStatus = "error"
	Finished OperationStatus = "finished"
	Pending  OperationStatus = "pending"
	Started  OperationStatus = "started"
)

// AlbumCoverResponse defines model for AlbumCoverResponse.
type AlbumCoverResponse struct {
	AlbumId int32 `json:"album_id"`
}

// AlbumCreateRequest defines model for AlbumCreateRequest.
type AlbumCreateRequest struct {
	AlbumCover      *openapi_types.File `json:"album_cover,omitempty"`
	AlbumName       string              `json:"album_name"`
	ArtistId        int32               `json:"artist_id"`
	ReleaseFullDate *openapi_types.Date `json:"release_full_date,omitempty"`
	ReleaseYear     *int32              `json:"release_year,omitempty"`
}

// AlbumCreateResponse defines model for AlbumCreateResponse.
type AlbumCreateResponse struct {
	AlbumId       int32 `json:"album_id"`
	CoverUploaded bool  `json:"cover_uploaded"`
}

// AlbumDeleteResponse defines model for AlbumDeleteResponse.
type AlbumDeleteResponse struct {
	AlbumId int32 `json:"album_id"`
}

// AlbumInfoResponse defines model for AlbumInfoResponse.
type AlbumInfoResponse struct {
	AlbumId         int32               `json:"album_id"`
	AlbumName       string              `json:"album_name"`
	ReleaseFullDate *openapi_types.Date `json:"release_full_date"`
	ReleaseYear     *int32              `json:"release_year"`
	Tracks          []int32             `json:"tracks"`
}

// ArtistCreateRequest defines model for ArtistCreateRequest.
type ArtistCreateRequest struct {
	ArtistImage *openapi_types.File `json:"artist_image,omitempty"`
	ArtistName  string              `json:"artist_name"`
}

// ArtistCreateResponse defines model for ArtistCreateResponse.
type ArtistCreateResponse struct {
	ArtistId      int32 `json:"artist_id"`
	CoverUploaded bool  `json:"cover_uploaded"`
}

// ArtistDeleteResponse defines model for ArtistDeleteResponse.
type ArtistDeleteResponse struct {
	ArtistId int32 `json:"artist_id"`
}

// ArtistImageResponse defines model for ArtistImageResponse.
type ArtistImageResponse struct {
	ArtistId int32 `json:"artist_id"`
}

// ArtistInfoResponse defines model for ArtistInfoResponse.
type ArtistInfoResponse struct {
	ArtistAlbums []int32 `json:"artist_albums"`
	ArtistId     int32   `json:"artist_id"`
	ArtistName   string  `json:"artist_name"`
}

// BackupStatusResponse defines model for BackupStatusResponse.
type BackupStatusResponse struct {
	BackupId                string          `json:"backup_id"`
	Error                   *string         `json:"error"`
	IncludeImages           bool            `json:"include_images"`
	IncludeTranscodedTracks bool            `json:"include_transcoded_tracks"`
	SizeBytes               *int64          `json:"size_bytes,omitempty"`
	Status                  OperationStatus `json:"status"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ExtendedPlaylist defines model for ExtendedPlaylist.
type ExtendedPlaylist struct {
	PlaylistId      int32                        `json:"playlist_id"`
	PlaylistName    string                       `json:"playlist_name"`
	PlaylistOwnerId int32                        `json:"playlist_owner_id"`
	PlaylistType    ExtendedPlaylistPlaylistType `json:"playlist_type"`
}

// ExtendedPlaylistPlaylistType defines model for ExtendedPlaylist.PlaylistType.
type ExtendedPlaylistPlaylistType string

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Msg string `json:"msg"`
}

// OperationStatus defines model for OperationStatus.
type OperationStatus string

// PasswordResetConfirmRequest defines model for PasswordResetConfirmRequest.
type PasswordResetConfirmRequest struct {
	Code        string              `json:"code"`
	Email       openapi_types.Email `json:"email"`
	NewPassword string              `json:"new_password"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// PlaylistCoverResponse defines model for PlaylistCoverResponse.
type PlaylistCoverResponse struct {
	PlaylistId int32 `json:"playlist_id"`
}

// PlaylistCreateRequest defines model for PlaylistCreateRequest.
type PlaylistCreateRequest struct {
	IsPublic      bool                `json:"is_public"`
	OwnerId       int32               `json:"owner_id"`
	PlaylistCover *openapi_types.File `json:"playlist_cover,omitempty"`
	PlaylistName  string              `json:"playlist_name"`
}

// PlaylistCreateResponse defines model for PlaylistCreateResponse.
type PlaylistCreateResponse struct {
	CoverUploaded bool  `json:"cover_uploaded"`
	PlaylistId    int32 `json:"playlist_id"`
}

// PlaylistDeleteResponse defines model for PlaylistDeleteResponse.
type PlaylistDeleteResponse struct {
	PlaylistId int32 `json:"playlist_id"`
}

// PlaylistResponse defines model for PlaylistResponse.
type PlaylistResponse struct {
	PlaylistId   int32  `json:"playlist_id"`
	PlaylistName string `json:"playlist_name"`
}

// PlaylistRevokeAccessRequest defines model for PlaylistRevokeAccessRequest.
type PlaylistRevokeAccessRequest struct {
	UserId int32 `json:"user_id"`
}

// PlaylistShareRequest defines model for PlaylistShareRequest.
type PlaylistShareRequest struct {
	HasWritePermission bool    `json:"has_write_permission"`
	ShareWithUsers     []int32 `json:"share_with_users"`
}

// PlaylistUpdateRequest defines model for PlaylistUpdateRequest.
type PlaylistUpdateRequest struct {
	PlaylistName string `json:"playlist_name"`
}

// PlaylistWithTracksResponse defines model for PlaylistWithTracksResponse.
type PlaylistWithTracksResponse struct {
	PlaylistId   int32   `json:"playlist_id"`
	PlaylistName string  `json:"playlist_name"`
	SharedWith   []int32 `json:"shared_with"`
	Tracks       []int32 `json:"tracks"`
}

// Playlists defines model for Playlists.
type Playlists = []ExtendedPlaylist

// RestoreStatusResponse defines model for RestoreStatusResponse.
type RestoreStatusResponse struct {
	Error     *string         `json:"error"`
	RestoreId string          `json:"restore_id"`
	Status    OperationStatus `json:"status"`
}

// SimpleUser defines model for SimpleUser.
type SimpleUser struct {
	Id       int32  `json:"id"`
	Username string `json:"username"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	TokenType    string `json:"token_type"`
	UserId       int32  `json:"user_id"`
}

// TrackMetadata defines model for TrackMetadata.
type TrackMetadata struct {
	AlbumId             int32   `json:"album_id"`
	ArtistId            int32   `json:"artist_id"`
	DurationMs          int32   `json:"duration_ms"`
	Name                string  `json:"name"`
	TrackFastPreset     *string `json:"track_fast_preset,omitempty"`
	TrackHighPreset     *string `json:"track_high_preset,omitempty"`
	TrackId             int32   `json:"track_id"`
	TrackLosslessPreset *string `json:"track_lossless_preset,omitempty"`
	TrackStandardPreset *string `json:"track_standard_preset,omitempty"`
}

// TrackUploadRequest defines model for TrackUploadRequest.
type TrackUploadRequest struct {
	AlbumId             *int32             `json:"album_id,omitempty"`
	ArtistId            int32              `json:"artist_id"`
	IsGloballyAvailable *bool              `json:"is_globally_available,omitempty"`
	IsSingle            *bool              `json:"is_single,omitempty"`
	Name                string             `json:"name"`
	Track               openapi_types.File `json:"track"`
}

// TrackUploadSuccessResponse defines model for TrackUploadSuccessResponse.
type TrackUploadSuccessResponse struct {
	TrackId int32 `json:"track_id"`
}

// UpdateTokenRequest defines model for UpdateTokenRequest.
type UpdateTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// UserAuth defines model for UserAuth.
type UserAuth struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserChangePassword defines model for UserChangePassword.
type UserChangePassword struct {
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// UserReturn defines model for UserReturn.
type UserReturn struct {
	Email       *string `json:"email"`
	Id          int32   `json:"id"`
	IsSuperuser bool    `json:"is_superuser"`
	Username    string  `json:"username"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	NewEmail    *openapi_types.Email `json:"new_email,omitempty"`
	NewUsername *string              `json:"new_username,omitempty"`
}

// Users defines model for Users.
type Users = []SimpleUser

// GetAllArtistsParams defines parameters for GetAllArtists.
type GetAllArtistsParams struct {
	// StartsWith Query parameter for searching or filtering artists.
	StartsWith *string `form:"starts_with,omitempty" json:"starts_with,omitempty"`

	// Limit Maximum number of artists to return.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// BackupParams defines parameters for Backup.
type BackupParams struct {
	IncludeImages           *bool `form:"include_images,omitempty" json:"include_images,omitempty"`
	IncludeTranscodedTracks *bool `form:"include_transcoded_tracks,omitempty" json:"include_transcoded_tracks,omitempty"`
}

// GetPlaylistsParams defines parameters for GetPlaylists.
type GetPlaylistsParams struct {
	IncludePublic *bool `form:"include_public,omitempty" json:"include_public,omitempty"`
	IncludeShared *bool `form:"include_shared,omitempty" json:"include_shared,omitempty"`
	IncludeOwned  *bool `form:"include_owned,omitempty" json:"include_owned,omitempty"`
}

// AddTrackToPlaylistJSONBody defines parameters for AddTrackToPlaylist.
type AddTrackToPlaylistJSONBody struct {
	TrackId int32 `json:"track_id"`
}

// DownloadTrackParams defines parameters for DownloadTrack.
type DownloadTrackParams struct {
	// Quality Preferred quality. If unavailable, the server falls back to the closest available preset, then to the original track file.
	Quality *string `form:"quality,omitempty" json:"quality,omitempty"`
}

// DownloadTrackHeadParams defines parameters for DownloadTrackHead.
type DownloadTrackHeadParams struct {
	// Quality Preferred quality. If unavailable, the server falls back to the closest available preset, then to the original track file.
	Quality *string `form:"quality,omitempty" json:"quality,omitempty"`
}

// StreamTrackParams defines parameters for StreamTrack.
type StreamTrackParams struct {
	// Quality Preferred quality. If unavailable, the server falls back to the closest available preset, then to the original track file.
	Quality *string `form:"quality,omitempty" json:"quality,omitempty"`
}

// StreamTrackHeadParams defines parameters for StreamTrackHead.
type StreamTrackHeadParams struct {
	// Quality Preferred quality. If unavailable, the server falls back to the closest available preset, then to the original track file.
	Quality *string `form:"quality,omitempty" json:"quality,omitempty"`
}

// CreateAlbumMultipartRequestBody defines body for CreateAlbum for multipart/form-data ContentType.
type CreateAlbumMultipartRequestBody = AlbumCreateRequest

// CreateArtistMultipartRequestBody defines body for CreateArtist for multipart/form-data ContentType.
type CreateArtistMultipartRequestBody = ArtistCreateRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = UserAuth

// ConfirmPasswordResetJSONRequestBody defines body for ConfirmPasswordReset for application/json ContentType.
type ConfirmPasswordResetJSONRequestBody = PasswordResetConfirmRequest

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = UpdateTokenRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = UserAuth

// CreatePlaylistMultipartRequestBody defines body for CreatePlaylist for multipart/form-data ContentType.
type CreatePlaylistMultipartRequestBody = PlaylistCreateRequest

// UpdatePlaylistJSONRequestBody defines body for UpdatePlaylist for application/json ContentType.
type UpdatePlaylistJSONRequestBody = PlaylistUpdateRequest

// AddTrackToPlaylistJSONRequestBody defines body for AddTrackToPlaylist for application/json ContentType.
type AddTrackToPlaylistJSONRequestBody AddTrackToPlaylistJSONBody

// RevokePlaylistJSONRequestBody defines body for RevokePlaylist for application/json ContentType.
type RevokePlaylistJSONRequestBody = PlaylistRevokeAccessRequest

// SharePlaylistJSONRequestBody defines body for SharePlaylist for application/json ContentType.
type SharePlaylistJSONRequestBody = PlaylistShareRequest

// UploadTrackMultipartRequestBody defines body for UploadTrack for multipart/form-data ContentType.
type UploadTrackMultipartRequestBody = TrackUploadRequest

// ChangeUserJSONRequestBody defines body for ChangeUser for application/json ContentType.
type ChangeUserJSONRequestBody = UserUpdate

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = UserChangePassword

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Creates a new album.
	// (POST /albums)
	CreateAlbum(w http.ResponseWriter, r *http.Request)
	// Deletes an album by ID.
	// (DELETE /albums/{albumId})
	DeleteAlbum(w http.ResponseWriter, r *http.Request, albumId int32)
	// Gets album information.
	// (GET /albums/{albumId})
	GetAlbum(w http.ResponseWriter, r *http.Request, albumId int32)

	// (DELETE /albums/{albumId}/cover)
	DeleteAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32)

	// (GET /albums/{albumId}/cover)
	GetAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32)

	// (POST /albums/{albumId}/cover)
	UploadAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32)
	// Removes a track from an album.
	// (DELETE /albums/{albumId}/tracks/{trackId})
	DeleteTrackFromAlbum(w http.ResponseWriter, r *http.Request, albumId int32, trackId int32)
	// Gets a list of all artists.
	// (GET /artists)
	GetAllArtists(w http.ResponseWriter, r *http.Request, params GetAllArtistsParams)
	// Creates a new artist.
	// (POST /artists)
	CreateArtist(w http.ResponseWriter, r *http.Request)
	// Deletes an artist by ID.
	// (DELETE /artists/{artistId})
	DeleteArtist(w http.ResponseWriter, r *http.Request, artistId int32)
	// Gets artist information.
	// (GET /artists/{artistId})
	GetArtist(w http.ResponseWriter, r *http.Request, artistId int32)

	// (DELETE /artists/{artistId}/image)
	DeleteArtistImage(w http.ResponseWriter, r *http.Request, artistId int32)

	// (GET /artists/{artistId}/image)
	GetArtistImage(w http.ResponseWriter, r *http.Request, artistId int32)

	// (POST /artists/{artistId}/image)
	UploadArtistImage(w http.ResponseWriter, r *http.Request, artistId int32)
	// Logs a user into their account.
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Resets a password using the code sent by email.
	// (POST /auth/password-reset/confirm)
	ConfirmPasswordReset(w http.ResponseWriter, r *http.Request)
	// Requests a password reset code by email.
	// (POST /auth/password-reset/request)
	RequestPasswordReset(w http.ResponseWriter, r *http.Request)
	// Refreshes JWT tokens.
	// (POST /auth/refresh)
	RefreshTokens(w http.ResponseWriter, r *http.Request)
	// Registers a new user.
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)

	// (POST /backup)
	Backup(w http.ResponseWriter, r *http.Request, params BackupParams)

	// (GET /backup/{backupId})
	GetBackupStatus(w http.ResponseWriter, r *http.Request, backupId string)

	// (GET /backup/{backupId}/download)
	DownloadBackup(w http.ResponseWriter, r *http.Request, backupId string)
	// Checks whether the server is alive.
	// (GET /ping)
	Ping(w http.ResponseWriter, r *http.Request)
	// Gets all playlists available to the user.
	// (GET /playlists)
	GetPlaylists(w http.ResponseWriter, r *http.Request, params GetPlaylistsParams)
	// Creates a new playlist.
	// (POST /playlists)
	CreatePlaylist(w http.ResponseWriter, r *http.Request)
	// Deletes a playlist by ID.
	// (DELETE /playlists/{playlistId})
	DeletePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32)
	// Gets playlist information.
	// (GET /playlists/{playlistId})
	GetPlaylist(w http.ResponseWriter, r *http.Request, playlistId int32)
	// Updates a playlist.
	// (PATCH /playlists/{playlistId})
	UpdatePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32)
	// Adds a track to a playlist.
	// (POST /playlists/{playlistId})
	AddTrackToPlaylist(w http.ResponseWriter, r *http.Request, playlistId int32)

	// (DELETE /playlists/{playlistId}/cover)
	DeletePlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32)

	// (GET /playlists/{playlistId}/cover)
	GetPlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32)

	// (POST /playlists/{playlistId}/cover)
	UploadPlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32)

	// (POST /playlists/{playlistId}/revoke)
	RevokePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32)

	// (POST /playlists/{playlistId}/share)
	SharePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32)
	// Removes a track from a playlist.
	// (DELETE /playlists/{playlistId}/tracks/{trackId})
	DeleteTrackFromPlaylist(w http.ResponseWriter, r *http.Request, playlistId int32, trackId int32)

	// (POST /restore)
	Restore(w http.ResponseWriter, r *http.Request)

	// (GET /restore/{restoreId})
	GetRestoreStatus(w http.ResponseWriter, r *http.Request, restoreId string)
	// Gets metadata for all uploaded tracks.
	// (GET /tracks)
	GetTracks(w http.ResponseWriter, r *http.Request)
	// Uploads a new track, queues transcoding, and stores it.
	// (POST /tracks)
	UploadTrack(w http.ResponseWriter, r *http.Request)
	// Downloads a track file.
	// (GET /tracks/{id}/download)
	DownloadTrack(w http.ResponseWriter, r *http.Request, id int32, params DownloadTrackParams)
	// Gets track metadata required for download.
	// (HEAD /tracks/{id}/download)
	DownloadTrackHead(w http.ResponseWriter, r *http.Request, id int32, params DownloadTrackHeadParams)
	// Streams a track.
	// (GET /tracks/{id}/stream)
	StreamTrack(w http.ResponseWriter, r *http.Request, id int32, params StreamTrackParams)
	// Gets track metadata required for streaming.
	// (HEAD /tracks/{id}/stream)
	StreamTrackHead(w http.ResponseWriter, r *http.Request, id int32, params StreamTrackHeadParams)
	// Deletes a track.
	// (DELETE /tracks/{trackId})
	DeleteTrack(w http.ResponseWriter, r *http.Request, trackId int32)
	// Gets track metadata.
	// (GET /tracks/{trackId})
	GetTrackMeta(w http.ResponseWriter, r *http.Request, trackId int32)
	// Gets all user IDs and usernames.
	// (GET /users)
	GetAllUsers(w http.ResponseWriter, r *http.Request)
	// Gets a user by ID.
	// (GET /users/{userId})
	GetUser(w http.ResponseWriter, r *http.Request, userId int32)
	// Updates a user.
	// (PATCH /users/{userId})
	ChangeUser(w http.ResponseWriter, r *http.Request, userId int32)
	// Deletes the current avatar.
	// (DELETE /users/{userId}/avatar)
	DeleteUserAvatar(w http.ResponseWriter, r *http.Request, userId int32)
	// Gets the uploaded user avatar.
	// (GET /users/{userId}/avatar)
	GetUserAvatar(w http.ResponseWriter, r *http.Request, userId int32)
	// Uploads a new user avatar to the server.
	// (POST /users/{userId}/avatar)
	UploadUserAvatar(w http.ResponseWriter, r *http.Request, userId int32)
	// Changes a user's password.
	// (PATCH /users/{userId}/change_password)
	ChangePassword(w http.ResponseWriter, r *http.Request, userId int32)
	// Gets a user by ID.
	// (GET /users/{userId}/simple)
	GetSimpleUser(w http.ResponseWriter, r *http.Request, userId int32)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Creates a new album.
// (POST /albums)
func (_ Unimplemented) CreateAlbum(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deletes an album by ID.
// (DELETE /albums/{albumId})
func (_ Unimplemented) DeleteAlbum(w http.ResponseWriter, r *http.Request, albumId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets album information.
// (GET /albums/{albumId})
func (_ Unimplemented) GetAlbum(w http.ResponseWriter, r *http.Request, albumId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /albums/{albumId}/cover)
func (_ Unimplemented) DeleteAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /albums/{albumId}/cover)
func (_ Unimplemented) GetAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /albums/{albumId}/cover)
func (_ Unimplemented) UploadAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Removes a track from an album.
// (DELETE /albums/{albumId}/tracks/{trackId})
func (_ Unimplemented) DeleteTrackFromAlbum(w http.ResponseWriter, r *http.Request, albumId int32, trackId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets a list of all artists.
// (GET /artists)
func (_ Unimplemented) GetAllArtists(w http.ResponseWriter, r *http.Request, params GetAllArtistsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Creates a new artist.
// (POST /artists)
func (_ Unimplemented) CreateArtist(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deletes an artist by ID.
// (DELETE /artists/{artistId})
func (_ Unimplemented) DeleteArtist(w http.ResponseWriter, r *http.Request, artistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets artist information.
// (GET /artists/{artistId})
func (_ Unimplemented) GetArtist(w http.ResponseWriter, r *http.Request, artistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /artists/{artistId}/image)
func (_ Unimplemented) DeleteArtistImage(w http.ResponseWriter, r *http.Request, artistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /artists/{artistId}/image)
func (_ Unimplemented) GetArtistImage(w http.ResponseWriter, r *http.Request, artistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /artists/{artistId}/image)
func (_ Unimplemented) UploadArtistImage(w http.ResponseWriter, r *http.Request, artistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logs a user into their account.
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resets a password using the code sent by email.
// (POST /auth/password-reset/confirm)
func (_ Unimplemented) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Requests a password reset code by email.
// (POST /auth/password-reset/request)
func (_ Unimplemented) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refreshes JWT tokens.
// (POST /auth/refresh)
func (_ Unimplemented) RefreshTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Registers a new user.
// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /backup)
func (_ Unimplemented) Backup(w http.ResponseWriter, r *http.Request, params BackupParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /backup/{backupId})
func (_ Unimplemented) GetBackupStatus(w http.ResponseWriter, r *http.Request, backupId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /backup/{backupId}/download)
func (_ Unimplemented) DownloadBackup(w http.ResponseWriter, r *http.Request, backupId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Checks whether the server is alive.
// (GET /ping)
func (_ Unimplemented) Ping(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets all playlists available to the user.
// (GET /playlists)
func (_ Unimplemented) GetPlaylists(w http.ResponseWriter, r *http.Request, params GetPlaylistsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Creates a new playlist.
// (POST /playlists)
func (_ Unimplemented) CreatePlaylist(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deletes a playlist by ID.
// (DELETE /playlists/{playlistId})
func (_ Unimplemented) DeletePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets playlist information.
// (GET /playlists/{playlistId})
func (_ Unimplemented) GetPlaylist(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Updates a playlist.
// (PATCH /playlists/{playlistId})
func (_ Unimplemented) UpdatePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Adds a track to a playlist.
// (POST /playlists/{playlistId})
func (_ Unimplemented) AddTrackToPlaylist(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /playlists/{playlistId}/cover)
func (_ Unimplemented) DeletePlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /playlists/{playlistId}/cover)
func (_ Unimplemented) GetPlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /playlists/{playlistId}/cover)
func (_ Unimplemented) UploadPlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /playlists/{playlistId}/revoke)
func (_ Unimplemented) RevokePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /playlists/{playlistId}/share)
func (_ Unimplemented) SharePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Removes a track from a playlist.
// (DELETE /playlists/{playlistId}/tracks/{trackId})
func (_ Unimplemented) DeleteTrackFromPlaylist(w http.ResponseWriter, r *http.Request, playlistId int32, trackId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /restore)
func (_ Unimplemented) Restore(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /restore/{restoreId})
func (_ Unimplemented) GetRestoreStatus(w http.ResponseWriter, r *http.Request, restoreId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets metadata for all uploaded tracks.
// (GET /tracks)
func (_ Unimplemented) GetTracks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Uploads a new track, queues transcoding, and stores it.
// (POST /tracks)
func (_ Unimplemented) UploadTrack(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Downloads a track file.
// (GET /tracks/{id}/download)
func (_ Unimplemented) DownloadTrack(w http.ResponseWriter, r *http.Request, id int32, params DownloadTrackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets track metadata required for download.
// (HEAD /tracks/{id}/download)
func (_ Unimplemented) DownloadTrackHead(w http.ResponseWriter, r *http.Request, id int32, params DownloadTrackHeadParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Streams a track.
// (GET /tracks/{id}/stream)
func (_ Unimplemented) StreamTrack(w http.ResponseWriter, r *http.Request, id int32, params StreamTrackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets track metadata required for streaming.
// (HEAD /tracks/{id}/stream)
func (_ Unimplemented) StreamTrackHead(w http.ResponseWriter, r *http.Request, id int32, params StreamTrackHeadParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deletes a track.
// (DELETE /tracks/{trackId})
func (_ Unimplemented) DeleteTrack(w http.ResponseWriter, r *http.Request, trackId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets track metadata.
// (GET /tracks/{trackId})
func (_ Unimplemented) GetTrackMeta(w http.ResponseWriter, r *http.Request, trackId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets all user IDs and usernames.
// (GET /users)
func (_ Unimplemented) GetAllUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets a user by ID.
// (GET /users/{userId})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Updates a user.
// (PATCH /users/{userId})
func (_ Unimplemented) ChangeUser(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deletes the current avatar.
// (DELETE /users/{userId}/avatar)
func (_ Unimplemented) DeleteUserAvatar(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets the uploaded user avatar.
// (GET /users/{userId}/avatar)
func (_ Unimplemented) GetUserAvatar(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Uploads a new user avatar to the server.
// (POST /users/{userId}/avatar)
func (_ Unimplemented) UploadUserAvatar(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Changes a user's password.
// (PATCH /users/{userId}/change_password)
func (_ Unimplemented) ChangePassword(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Gets a user by ID.
// (GET /users/{userId}/simple)
func (_ Unimplemented) GetSimpleUser(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAlbum operation middleware
func (siw *ServerInterfaceWrapper) CreateAlbum(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAlbum(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAlbum operation middleware
func (siw *ServerInterfaceWrapper) DeleteAlbum(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId int32

	err = runtime.BindStyledParameterWithOptions("simple", "albumId", chi.URLParam(r, "albumId"), &albumId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "albumId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAlbum(w, r, albumId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAlbum operation middleware
func (siw *ServerInterfaceWrapper) GetAlbum(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId int32

	err = runtime.BindStyledParameterWithOptions("simple", "albumId", chi.URLParam(r, "albumId"), &albumId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "albumId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlbum(w, r, albumId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAlbumCover operation middleware
func (siw *ServerInterfaceWrapper) DeleteAlbumCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId int32

	err = runtime.BindStyledParameterWithOptions("simple", "albumId", chi.URLParam(r, "albumId"), &albumId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "albumId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAlbumCover(w, r, albumId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAlbumCover operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId int32

	err = runtime.BindStyledParameterWithOptions("simple", "albumId", chi.URLParam(r, "albumId"), &albumId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "albumId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlbumCover(w, r, albumId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadAlbumCover operation middleware
func (siw *ServerInterfaceWrapper) UploadAlbumCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId int32

	err = runtime.BindStyledParameterWithOptions("simple", "albumId", chi.URLParam(r, "albumId"), &albumId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "albumId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadAlbumCover(w, r, albumId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrackFromAlbum operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrackFromAlbum(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId int32

	err = runtime.BindStyledParameterWithOptions("simple", "albumId", chi.URLParam(r, "albumId"), &albumId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "albumId", Err: err})
		return
	}

	// ------------- Path parameter "trackId" -------------
	var trackId int32

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrackFromAlbum(w, r, albumId, trackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllArtists operation middleware
func (siw *ServerInterfaceWrapper) GetAllArtists(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllArtistsParams

	// ------------- Optional query parameter "starts_with" -------------

	err = runtime.BindQueryParameter("form", true, false, "starts_with", r.URL.Query(), &params.StartsWith)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starts_with", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllArtists(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateArtist operation middleware
func (siw *ServerInterfaceWrapper) CreateArtist(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateArtist(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArtist operation middleware
func (siw *ServerInterfaceWrapper) DeleteArtist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", chi.URLParam(r, "artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArtist(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtist operation middleware
func (siw *ServerInterfaceWrapper) GetArtist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", chi.URLParam(r, "artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtist(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArtistImage operation middleware
func (siw *ServerInterfaceWrapper) DeleteArtistImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", chi.URLParam(r, "artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArtistImage(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtistImage operation middleware
func (siw *ServerInterfaceWrapper) GetArtistImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", chi.URLParam(r, "artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtistImage(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadArtistImage operation middleware
func (siw *ServerInterfaceWrapper) UploadArtistImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", chi.URLParam(r, "artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadArtistImage(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshTokens operation middleware
func (siw *ServerInterfaceWrapper) RefreshTokens(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Backup operation middleware
func (siw *ServerInterfaceWrapper) Backup(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params BackupParams

	// ------------- Optional query parameter "include_images" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_images", r.URL.Query(), &params.IncludeImages)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_images", Err: err})
		return
	}

	// ------------- Optional query parameter "include_transcoded_tracks" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_transcoded_tracks", r.URL.Query(), &params.IncludeTranscodedTracks)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_transcoded_tracks", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Backup(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBackupStatus operation middleware
func (siw *ServerInterfaceWrapper) GetBackupStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backupId" -------------
	var backupId string

	err = runtime.BindStyledParameterWithOptions("simple", "backupId", chi.URLParam(r, "backupId"), &backupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backupId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBackupStatus(w, r, backupId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadBackup operation middleware
func (siw *ServerInterfaceWrapper) DownloadBackup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "backupId" -------------
	var backupId string

	err = runtime.BindStyledParameterWithOptions("simple", "backupId", chi.URLParam(r, "backupId"), &backupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "backupId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadBackup(w, r, backupId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylists operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylists(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPlaylistsParams

	// ------------- Optional query parameter "include_public" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_public", r.URL.Query(), &params.IncludePublic)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_public", Err: err})
		return
	}

	// ------------- Optional query parameter "include_shared" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_shared", r.URL.Query(), &params.IncludeShared)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_shared", Err: err})
		return
	}

	// ------------- Optional query parameter "include_owned" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_owned", r.URL.Query(), &params.IncludeOwned)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_owned", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylists(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlaylist operation middleware
func (siw *ServerInterfaceWrapper) CreatePlaylist(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlaylist(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePlaylist operation middleware
func (siw *ServerInterfaceWrapper) DeletePlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylist operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePlaylist operation middleware
func (siw *ServerInterfaceWrapper) UpdatePlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTrackToPlaylist operation middleware
func (siw *ServerInterfaceWrapper) AddTrackToPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTrackToPlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePlaylistCover operation middleware
func (siw *ServerInterfaceWrapper) DeletePlaylistCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePlaylistCover(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylistCover operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylistCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylistCover(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadPlaylistCover operation middleware
func (siw *ServerInterfaceWrapper) UploadPlaylistCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadPlaylistCover(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokePlaylist operation middleware
func (siw *ServerInterfaceWrapper) RevokePlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokePlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SharePlaylist operation middleware
func (siw *ServerInterfaceWrapper) SharePlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SharePlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrackFromPlaylist operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrackFromPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	// ------------- Path parameter "trackId" -------------
	var trackId int32

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrackFromPlaylist(w, r, playlistId, trackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Restore operation middleware
func (siw *ServerInterfaceWrapper) Restore(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Restore(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRestoreStatus operation middleware
func (siw *ServerInterfaceWrapper) GetRestoreStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "restoreId" -------------
	var restoreId string

	err = runtime.BindStyledParameterWithOptions("simple", "restoreId", chi.URLParam(r, "restoreId"), &restoreId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "restoreId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRestoreStatus(w, r, restoreId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTracks operation middleware
func (siw *ServerInterfaceWrapper) GetTracks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTracks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadTrack operation middleware
func (siw *ServerInterfaceWrapper) UploadTrack(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadTrack(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadTrack operation middleware
func (siw *ServerInterfaceWrapper) DownloadTrack(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadTrackParams

	// ------------- Optional query parameter "quality" -------------

	err = runtime.BindQueryParameter("form", true, false, "quality", r.URL.Query(), &params.Quality)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quality", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadTrack(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadTrackHead operation middleware
func (siw *ServerInterfaceWrapper) DownloadTrackHead(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params DownloadTrackHeadParams

	// ------------- Optional query parameter "quality" -------------

	err = runtime.BindQueryParameter("form", true, false, "quality", r.URL.Query(), &params.Quality)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quality", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadTrackHead(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamTrack operation middleware
func (siw *ServerInterfaceWrapper) StreamTrack(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamTrackParams

	// ------------- Optional query parameter "quality" -------------

	err = runtime.BindQueryParameter("form", true, false, "quality", r.URL.Query(), &params.Quality)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quality", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamTrack(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamTrackHead operation middleware
func (siw *ServerInterfaceWrapper) StreamTrackHead(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamTrackHeadParams

	// ------------- Optional query parameter "quality" -------------

	err = runtime.BindQueryParameter("form", true, false, "quality", r.URL.Query(), &params.Quality)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quality", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamTrackHead(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrack operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrack(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "trackId" -------------
	var trackId int32

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrack(w, r, trackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrackMeta operation middleware
func (siw *ServerInterfaceWrapper) GetTrackMeta(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "trackId" -------------
	var trackId int32

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrackMeta(w, r, trackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllUsers operation middleware
func (siw *ServerInterfaceWrapper) GetAllUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangeUser operation middleware
func (siw *ServerInterfaceWrapper) ChangeUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangeUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserAvatar(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) GetUserAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserAvatar(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) UploadUserAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadUserAvatar(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSimpleUser operation middleware
func (siw *ServerInterfaceWrapper) GetSimpleUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSimpleUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/albums", wrapper.CreateAlbum)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/albums/{albumId}", wrapper.DeleteAlbum)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/albums/{albumId}", wrapper.GetAlbum)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/albums/{albumId}/cover", wrapper.DeleteAlbumCover)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/albums/{albumId}/cover", wrapper.GetAlbumCover)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/albums/{albumId}/cover", wrapper.UploadAlbumCover)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/albums/{albumId}/tracks/{trackId}", wrapper.DeleteTrackFromAlbum)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/artists", wrapper.GetAllArtists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/artists", wrapper.CreateArtist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/artists/{artistId}", wrapper.DeleteArtist)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/artists/{artistId}", wrapper.GetArtist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/artists/{artistId}/image", wrapper.DeleteArtistImage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/artists/{artistId}/image", wrapper.GetArtistImage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/artists/{artistId}/image", wrapper.UploadArtistImage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password-reset/confirm", wrapper.ConfirmPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/password-reset/request", wrapper.RequestPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/backup", wrapper.Backup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/backup/{backupId}", wrapper.GetBackupStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/backup/{backupId}/download", wrapper.DownloadBackup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ping", wrapper.Ping)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/playlists", wrapper.GetPlaylists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/playlists", wrapper.CreatePlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/playlists/{playlistId}", wrapper.DeletePlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/playlists/{playlistId}", wrapper.GetPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/playlists/{playlistId}", wrapper.UpdatePlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/playlists/{playlistId}", wrapper.AddTrackToPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/playlists/{playlistId}/cover", wrapper.DeletePlaylistCover)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/playlists/{playlistId}/cover", wrapper.GetPlaylistCover)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/playlists/{playlistId}/cover", wrapper.UploadPlaylistCover)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/playlists/{playlistId}/revoke", wrapper.RevokePlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/playlists/{playlistId}/share", wrapper.SharePlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/playlists/{playlistId}/tracks/{trackId}", wrapper.DeleteTrackFromPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/restore", wrapper.Restore)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/restore/{restoreId}", wrapper.GetRestoreStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tracks", wrapper.GetTracks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tracks", wrapper.UploadTrack)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tracks/{id}/download", wrapper.DownloadTrack)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/tracks/{id}/download", wrapper.DownloadTrackHead)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tracks/{id}/stream", wrapper.StreamTrack)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/tracks/{id}/stream", wrapper.StreamTrackHead)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/tracks/{trackId}", wrapper.DeleteTrack)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tracks/{trackId}", wrapper.GetTrackMeta)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.GetAllUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{userId}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/users/{userId}", wrapper.ChangeUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{userId}/avatar", wrapper.DeleteUserAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{userId}/avatar", wrapper.GetUserAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/{userId}/avatar", wrapper.UploadUserAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/users/{userId}/change_password", wrapper.ChangePassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{userId}/simple", wrapper.GetSimpleUser)
	})

	return r
}
