// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for RestoreStatusResponseStatus.
const (
	Error    RestoreStatusResponseStatus = "error"
	Finished RestoreStatusResponseStatus = "finished"
	Pending  RestoreStatusResponseStatus = "pending"
	Started  RestoreStatusResponseStatus = "started"
)

// AlbumCoverResponse defines model for AlbumCoverResponse.
type AlbumCoverResponse struct {
	AlbumId int32 `json:"album_id"`
}

// AlbumCreateRequest defines model for AlbumCreateRequest.
type AlbumCreateRequest struct {
	AlbumCover      *openapi_types.File `json:"album_cover,omitempty"`
	AlbumName       string              `json:"album_name"`
	ArtistId        int32               `json:"artist_id"`
	ReleaseFullDate *openapi_types.Date `json:"release_full_date,omitempty"`
	ReleaseYear     *int32              `json:"release_year,omitempty"`
}

// AlbumCreateResponse defines model for AlbumCreateResponse.
type AlbumCreateResponse struct {
	AlbumId       int32 `json:"album_id"`
	CoverUploaded bool  `json:"cover_uploaded"`
}

// AlbumDeleteResponse defines model for AlbumDeleteResponse.
type AlbumDeleteResponse struct {
	AlbumId int32 `json:"album_id"`
}

// AlbumInfoResponse defines model for AlbumInfoResponse.
type AlbumInfoResponse struct {
	AlbumId         int32               `json:"album_id"`
	AlbumName       string              `json:"album_name"`
	CoverUrl        *string             `json:"cover_url,omitempty"`
	ReleaseFullDate *openapi_types.Date `json:"release_full_date"`
	ReleaseYear     *int32              `json:"release_year"`
	Tracks          []int32             `json:"tracks"`
}

// ArtistCreateRequest defines model for ArtistCreateRequest.
type ArtistCreateRequest struct {
	ArtistImage *openapi_types.File `json:"artist_image,omitempty"`
	ArtistName  string              `json:"artist_name"`
}

// ArtistCreateResponse defines model for ArtistCreateResponse.
type ArtistCreateResponse struct {
	ArtistId      int32 `json:"artist_id"`
	CoverUploaded bool  `json:"cover_uploaded"`
}

// ArtistDeleteResponse defines model for ArtistDeleteResponse.
type ArtistDeleteResponse struct {
	ArtistId int32 `json:"artist_id"`
}

// ArtistImageResponse defines model for ArtistImageResponse.
type ArtistImageResponse struct {
	ArtistId int32 `json:"artist_id"`
}

// ArtistInfoResponse defines model for ArtistInfoResponse.
type ArtistInfoResponse struct {
	ArtistAlbums []int32 `json:"artist_albums"`
	ArtistId     int32   `json:"artist_id"`
	ArtistName   string  `json:"artist_name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Msg string `json:"msg"`
}

// PlaylistCoverResponse defines model for PlaylistCoverResponse.
type PlaylistCoverResponse struct {
	PlaylistId int32 `json:"playlist_id"`
}

// PlaylistCreateRequest defines model for PlaylistCreateRequest.
type PlaylistCreateRequest struct {
	IsPublic      bool                `json:"is_public"`
	OwnerId       int32               `json:"owner_id"`
	PlaylistCover *openapi_types.File `json:"playlist_cover,omitempty"`
	PlaylistName  string              `json:"playlist_name"`
}

// PlaylistCreateResponse defines model for PlaylistCreateResponse.
type PlaylistCreateResponse struct {
	CoverUploaded bool  `json:"cover_uploaded"`
	PlaylistId    int32 `json:"playlist_id"`
}

// PlaylistDeleteResponse defines model for PlaylistDeleteResponse.
type PlaylistDeleteResponse struct {
	PlaylistId int32 `json:"playlist_id"`
}

// PlaylistResponse defines model for PlaylistResponse.
type PlaylistResponse struct {
	PlaylistId   int32  `json:"playlist_id"`
	PlaylistName string `json:"playlist_name"`
}

// PlaylistWithTracksResponse defines model for PlaylistWithTracksResponse.
type PlaylistWithTracksResponse struct {
	CoverUrl     *string `json:"cover_url,omitempty"`
	PlaylistId   int32   `json:"playlist_id"`
	PlaylistName string  `json:"playlist_name"`
	Tracks       []int32 `json:"tracks"`
}

// Playlists defines model for Playlists.
type Playlists = []PlaylistResponse

// RestoreStatusResponse defines model for RestoreStatusResponse.
type RestoreStatusResponse struct {
	Error     *string                     `json:"error"`
	RestoreId string                      `json:"restore_id"`
	Status    RestoreStatusResponseStatus `json:"status"`
}

// RestoreStatusResponseStatus defines model for RestoreStatusResponse.Status.
type RestoreStatusResponseStatus string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	TokenType    string `json:"token_type"`
	UserId       int32  `json:"user_id"`
}

// TrackMetadata defines model for TrackMetadata.
type TrackMetadata struct {
	AlbumId             int32   `json:"album_id"`
	ArtistId            int32   `json:"artist_id"`
	CoverUrl            *string `json:"cover_url,omitempty"`
	DurationMs          int32   `json:"duration_ms"`
	Name                string  `json:"name"`
	TrackFastPreset     *string `json:"track_fast_preset,omitempty"`
	TrackHighPreset     *string `json:"track_high_preset,omitempty"`
	TrackId             int32   `json:"track_id"`
	TrackLosslessPreset *string `json:"track_lossless_preset,omitempty"`
	TrackStandardPreset *string `json:"track_standard_preset,omitempty"`
}

// TrackUploadRequest defines model for TrackUploadRequest.
type TrackUploadRequest struct {
	AlbumId             *int32             `json:"album_id,omitempty"`
	ArtistId            int32              `json:"artist_id"`
	IsGloballyAvailable *bool              `json:"is_globally_available,omitempty"`
	IsSingle            *bool              `json:"is_single,omitempty"`
	Name                string             `json:"name"`
	Track               openapi_types.File `json:"track"`
}

// TrackUploadSuccessResponse defines model for TrackUploadSuccessResponse.
type TrackUploadSuccessResponse struct {
	TrackId int32 `json:"track_id"`
}

// UpdateTokenRequest defines model for UpdateTokenRequest.
type UpdateTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// UserAuth defines model for UserAuth.
type UserAuth struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserChangePassword defines model for UserChangePassword.
type UserChangePassword struct {
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// UserReturn defines model for UserReturn.
type UserReturn struct {
	Email       *string `json:"email"`
	Id          int32   `json:"id"`
	IsSuperuser bool    `json:"is_superuser"`
	Username    string  `json:"username"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	NewEmail    string `json:"new_email"`
	NewUsername string `json:"new_username"`
}

// GetAllArtistsParams defines parameters for GetAllArtists.
type GetAllArtistsParams struct {
	// StartsWith query parameter for searching/filtering artists
	StartsWith *string `form:"starts_with,omitempty" json:"starts_with,omitempty"`

	// Limit limit on a number of artists
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// BackupParams defines parameters for Backup.
type BackupParams struct {
	IncludeImages           *bool `form:"include_images,omitempty" json:"include_images,omitempty"`
	IncludeTranscodedTracks *bool `form:"include_transcoded_tracks,omitempty" json:"include_transcoded_tracks,omitempty"`
}

// AddTrackToPlaylistJSONBody defines parameters for AddTrackToPlaylist.
type AddTrackToPlaylistJSONBody struct {
	TrackId int32 `json:"track_id"`
}

// StreamTrackParams defines parameters for StreamTrack.
type StreamTrackParams struct {
	Quality *string `form:"quality,omitempty" json:"quality,omitempty"`
}

// StreamTrackHeadParams defines parameters for StreamTrackHead.
type StreamTrackHeadParams struct {
	Quality *string `form:"quality,omitempty" json:"quality,omitempty"`
}

// CreateAlbumMultipartRequestBody defines body for CreateAlbum for multipart/form-data ContentType.
type CreateAlbumMultipartRequestBody = AlbumCreateRequest

// CreateArtistMultipartRequestBody defines body for CreateArtist for multipart/form-data ContentType.
type CreateArtistMultipartRequestBody = ArtistCreateRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = UserAuth

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = UpdateTokenRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = UserAuth

// CreatePlaylistMultipartRequestBody defines body for CreatePlaylist for multipart/form-data ContentType.
type CreatePlaylistMultipartRequestBody = PlaylistCreateRequest

// UpdatePlaylistJSONRequestBody defines body for UpdatePlaylist for application/json ContentType.
type UpdatePlaylistJSONRequestBody = PlaylistResponse

// AddTrackToPlaylistJSONRequestBody defines body for AddTrackToPlaylist for application/json ContentType.
type AddTrackToPlaylistJSONRequestBody AddTrackToPlaylistJSONBody

// UploadTrackMultipartRequestBody defines body for UploadTrack for multipart/form-data ContentType.
type UploadTrackMultipartRequestBody = TrackUploadRequest

// ChangeUserJSONRequestBody defines body for ChangeUser for application/json ContentType.
type ChangeUserJSONRequestBody = UserUpdate

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = UserChangePassword

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// creates new album
	// (POST /albums)
	CreateAlbum(w http.ResponseWriter, r *http.Request)
	// deletes album by id
	// (DELETE /albums/{albumId})
	DeleteAlbum(w http.ResponseWriter, r *http.Request, albumId int32)
	// get info about the album
	// (GET /albums/{albumId})
	GetAlbum(w http.ResponseWriter, r *http.Request, albumId int32)

	// (DELETE /albums/{albumId}/cover)
	DeleteAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32)

	// (GET /albums/{albumId}/cover)
	GetAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32)

	// (POST /albums/{albumId}/cover)
	UploadAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32)
	// get list of all artists
	// (GET /artists)
	GetAllArtists(w http.ResponseWriter, r *http.Request, params GetAllArtistsParams)
	// creates new artist
	// (POST /artists)
	CreateArtist(w http.ResponseWriter, r *http.Request)
	// deletes artist by id
	// (DELETE /artists/{artistId})
	DeleteArtist(w http.ResponseWriter, r *http.Request, artistId int32)
	// get info about artist
	// (GET /artists/{artistId})
	GetArtist(w http.ResponseWriter, r *http.Request, artistId int32)

	// (DELETE /artists/{artistId}/image)
	DeleteArtistImage(w http.ResponseWriter, r *http.Request, artistId int32)

	// (GET /artists/{artistId}/image)
	GetArtistImage(w http.ResponseWriter, r *http.Request, artistId int32)

	// (POST /artists/{artistId}/image)
	UploadArtistImage(w http.ResponseWriter, r *http.Request, artistId int32)
	// login user into account
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// update jwt tokens
	// (POST /auth/refresh)
	RefreshTokens(w http.ResponseWriter, r *http.Request)
	// register new user
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)

	// (GET /backup)
	Backup(w http.ResponseWriter, r *http.Request, params BackupParams)
	// route to test, that server is alive
	// (GET /ping)
	Ping(w http.ResponseWriter, r *http.Request)
	// get all user's playlist
	// (GET /playlists)
	GetPlaylists(w http.ResponseWriter, r *http.Request)
	// creates new playlist
	// (POST /playlists)
	CreatePlaylist(w http.ResponseWriter, r *http.Request)
	// deletes playlist by id
	// (DELETE /playlists/{playlistId})
	DeletePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32)
	// get info about playlist
	// (GET /playlists/{playlistId})
	GetPlaylist(w http.ResponseWriter, r *http.Request, playlistId int32)
	// update playlist
	// (PATCH /playlists/{playlistId})
	UpdatePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32)
	// add track to playlist
	// (POST /playlists/{playlistId})
	AddTrackToPlaylist(w http.ResponseWriter, r *http.Request, playlistId int32)

	// (DELETE /playlists/{playlistId}/cover)
	DeletePlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32)

	// (GET /playlists/{playlistId}/cover)
	GetPlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32)

	// (POST /playlists/{playlistId}/cover)
	UploadPlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32)

	// (POST /restore)
	Restore(w http.ResponseWriter, r *http.Request)

	// (GET /restore/{restoreId})
	GetRestoreStatus(w http.ResponseWriter, r *http.Request, restoreId string)
	// get all uploaded tracks meta
	// (GET /tracks)
	GetTracks(w http.ResponseWriter, r *http.Request)
	// uploads new track, make all transcoding stuff, stores it
	// (POST /tracks)
	UploadTrack(w http.ResponseWriter, r *http.Request)
	// getting track stream
	// (GET /tracks/{id}/stream)
	StreamTrack(w http.ResponseWriter, r *http.Request, id int32, params StreamTrackParams)
	// getting track metadata, needed for streaming
	// (HEAD /tracks/{id}/stream)
	StreamTrackHead(w http.ResponseWriter, r *http.Request, id int32, params StreamTrackHeadParams)
	// delete track
	// (DELETE /tracks/{trackId})
	DeleteTrack(w http.ResponseWriter, r *http.Request, trackId int32)
	// getting track metadata
	// (GET /tracks/{trackId})
	GetTrackMeta(w http.ResponseWriter, r *http.Request, trackId int32)
	// get user by id
	// (GET /users/{userId})
	GetUserById(w http.ResponseWriter, r *http.Request, userId int32)
	// update user
	// (PATCH /users/{userId})
	ChangeUser(w http.ResponseWriter, r *http.Request, userId int32)
	// delete current avatar
	// (DELETE /users/{userId}/avatar)
	DeleteUserAvatar(w http.ResponseWriter, r *http.Request, userId int32)
	// get uploaded avatar
	// (GET /users/{userId}/avatar)
	GetUserAvatar(w http.ResponseWriter, r *http.Request, userId int32)
	// upload new user's avatar to server
	// (POST /users/{userId}/avatar)
	UploadUserAvatar(w http.ResponseWriter, r *http.Request, userId int32)
	// change user's password
	// (PATCH /users/{userId}/change_password)
	ChangePassword(w http.ResponseWriter, r *http.Request, userId int32)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// creates new album
// (POST /albums)
func (_ Unimplemented) CreateAlbum(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// deletes album by id
// (DELETE /albums/{albumId})
func (_ Unimplemented) DeleteAlbum(w http.ResponseWriter, r *http.Request, albumId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// get info about the album
// (GET /albums/{albumId})
func (_ Unimplemented) GetAlbum(w http.ResponseWriter, r *http.Request, albumId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /albums/{albumId}/cover)
func (_ Unimplemented) DeleteAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /albums/{albumId}/cover)
func (_ Unimplemented) GetAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /albums/{albumId}/cover)
func (_ Unimplemented) UploadAlbumCover(w http.ResponseWriter, r *http.Request, albumId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// get list of all artists
// (GET /artists)
func (_ Unimplemented) GetAllArtists(w http.ResponseWriter, r *http.Request, params GetAllArtistsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// creates new artist
// (POST /artists)
func (_ Unimplemented) CreateArtist(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// deletes artist by id
// (DELETE /artists/{artistId})
func (_ Unimplemented) DeleteArtist(w http.ResponseWriter, r *http.Request, artistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// get info about artist
// (GET /artists/{artistId})
func (_ Unimplemented) GetArtist(w http.ResponseWriter, r *http.Request, artistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /artists/{artistId}/image)
func (_ Unimplemented) DeleteArtistImage(w http.ResponseWriter, r *http.Request, artistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /artists/{artistId}/image)
func (_ Unimplemented) GetArtistImage(w http.ResponseWriter, r *http.Request, artistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /artists/{artistId}/image)
func (_ Unimplemented) UploadArtistImage(w http.ResponseWriter, r *http.Request, artistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// login user into account
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// update jwt tokens
// (POST /auth/refresh)
func (_ Unimplemented) RefreshTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// register new user
// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /backup)
func (_ Unimplemented) Backup(w http.ResponseWriter, r *http.Request, params BackupParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// route to test, that server is alive
// (GET /ping)
func (_ Unimplemented) Ping(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// get all user's playlist
// (GET /playlists)
func (_ Unimplemented) GetPlaylists(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// creates new playlist
// (POST /playlists)
func (_ Unimplemented) CreatePlaylist(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// deletes playlist by id
// (DELETE /playlists/{playlistId})
func (_ Unimplemented) DeletePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// get info about playlist
// (GET /playlists/{playlistId})
func (_ Unimplemented) GetPlaylist(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// update playlist
// (PATCH /playlists/{playlistId})
func (_ Unimplemented) UpdatePlaylist(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// add track to playlist
// (POST /playlists/{playlistId})
func (_ Unimplemented) AddTrackToPlaylist(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /playlists/{playlistId}/cover)
func (_ Unimplemented) DeletePlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /playlists/{playlistId}/cover)
func (_ Unimplemented) GetPlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /playlists/{playlistId}/cover)
func (_ Unimplemented) UploadPlaylistCover(w http.ResponseWriter, r *http.Request, playlistId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /restore)
func (_ Unimplemented) Restore(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /restore/{restoreId})
func (_ Unimplemented) GetRestoreStatus(w http.ResponseWriter, r *http.Request, restoreId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// get all uploaded tracks meta
// (GET /tracks)
func (_ Unimplemented) GetTracks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// uploads new track, make all transcoding stuff, stores it
// (POST /tracks)
func (_ Unimplemented) UploadTrack(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// getting track stream
// (GET /tracks/{id}/stream)
func (_ Unimplemented) StreamTrack(w http.ResponseWriter, r *http.Request, id int32, params StreamTrackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// getting track metadata, needed for streaming
// (HEAD /tracks/{id}/stream)
func (_ Unimplemented) StreamTrackHead(w http.ResponseWriter, r *http.Request, id int32, params StreamTrackHeadParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// delete track
// (DELETE /tracks/{trackId})
func (_ Unimplemented) DeleteTrack(w http.ResponseWriter, r *http.Request, trackId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// getting track metadata
// (GET /tracks/{trackId})
func (_ Unimplemented) GetTrackMeta(w http.ResponseWriter, r *http.Request, trackId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// get user by id
// (GET /users/{userId})
func (_ Unimplemented) GetUserById(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// update user
// (PATCH /users/{userId})
func (_ Unimplemented) ChangeUser(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// delete current avatar
// (DELETE /users/{userId}/avatar)
func (_ Unimplemented) DeleteUserAvatar(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// get uploaded avatar
// (GET /users/{userId}/avatar)
func (_ Unimplemented) GetUserAvatar(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// upload new user's avatar to server
// (POST /users/{userId}/avatar)
func (_ Unimplemented) UploadUserAvatar(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// change user's password
// (PATCH /users/{userId}/change_password)
func (_ Unimplemented) ChangePassword(w http.ResponseWriter, r *http.Request, userId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateAlbum operation middleware
func (siw *ServerInterfaceWrapper) CreateAlbum(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAlbum(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAlbum operation middleware
func (siw *ServerInterfaceWrapper) DeleteAlbum(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId int32

	err = runtime.BindStyledParameterWithOptions("simple", "albumId", chi.URLParam(r, "albumId"), &albumId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "albumId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAlbum(w, r, albumId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAlbum operation middleware
func (siw *ServerInterfaceWrapper) GetAlbum(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId int32

	err = runtime.BindStyledParameterWithOptions("simple", "albumId", chi.URLParam(r, "albumId"), &albumId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "albumId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlbum(w, r, albumId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAlbumCover operation middleware
func (siw *ServerInterfaceWrapper) DeleteAlbumCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId int32

	err = runtime.BindStyledParameterWithOptions("simple", "albumId", chi.URLParam(r, "albumId"), &albumId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "albumId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAlbumCover(w, r, albumId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAlbumCover operation middleware
func (siw *ServerInterfaceWrapper) GetAlbumCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId int32

	err = runtime.BindStyledParameterWithOptions("simple", "albumId", chi.URLParam(r, "albumId"), &albumId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "albumId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAlbumCover(w, r, albumId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadAlbumCover operation middleware
func (siw *ServerInterfaceWrapper) UploadAlbumCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "albumId" -------------
	var albumId int32

	err = runtime.BindStyledParameterWithOptions("simple", "albumId", chi.URLParam(r, "albumId"), &albumId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "albumId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadAlbumCover(w, r, albumId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAllArtists operation middleware
func (siw *ServerInterfaceWrapper) GetAllArtists(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllArtistsParams

	// ------------- Optional query parameter "starts_with" -------------

	err = runtime.BindQueryParameter("form", true, false, "starts_with", r.URL.Query(), &params.StartsWith)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starts_with", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAllArtists(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateArtist operation middleware
func (siw *ServerInterfaceWrapper) CreateArtist(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateArtist(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArtist operation middleware
func (siw *ServerInterfaceWrapper) DeleteArtist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", chi.URLParam(r, "artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArtist(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtist operation middleware
func (siw *ServerInterfaceWrapper) GetArtist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", chi.URLParam(r, "artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtist(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteArtistImage operation middleware
func (siw *ServerInterfaceWrapper) DeleteArtistImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", chi.URLParam(r, "artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteArtistImage(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArtistImage operation middleware
func (siw *ServerInterfaceWrapper) GetArtistImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", chi.URLParam(r, "artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArtistImage(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadArtistImage operation middleware
func (siw *ServerInterfaceWrapper) UploadArtistImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "artistId" -------------
	var artistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "artistId", chi.URLParam(r, "artistId"), &artistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "artistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadArtistImage(w, r, artistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshTokens operation middleware
func (siw *ServerInterfaceWrapper) RefreshTokens(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Backup operation middleware
func (siw *ServerInterfaceWrapper) Backup(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params BackupParams

	// ------------- Optional query parameter "include_images" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_images", r.URL.Query(), &params.IncludeImages)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_images", Err: err})
		return
	}

	// ------------- Optional query parameter "include_transcoded_tracks" -------------

	err = runtime.BindQueryParameter("form", true, false, "include_transcoded_tracks", r.URL.Query(), &params.IncludeTranscodedTracks)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "include_transcoded_tracks", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Backup(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ping(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylists operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylists(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlaylist operation middleware
func (siw *ServerInterfaceWrapper) CreatePlaylist(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlaylist(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePlaylist operation middleware
func (siw *ServerInterfaceWrapper) DeletePlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylist operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePlaylist operation middleware
func (siw *ServerInterfaceWrapper) UpdatePlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddTrackToPlaylist operation middleware
func (siw *ServerInterfaceWrapper) AddTrackToPlaylist(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddTrackToPlaylist(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePlaylistCover operation middleware
func (siw *ServerInterfaceWrapper) DeletePlaylistCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePlaylistCover(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlaylistCover operation middleware
func (siw *ServerInterfaceWrapper) GetPlaylistCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlaylistCover(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadPlaylistCover operation middleware
func (siw *ServerInterfaceWrapper) UploadPlaylistCover(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "playlistId" -------------
	var playlistId int32

	err = runtime.BindStyledParameterWithOptions("simple", "playlistId", chi.URLParam(r, "playlistId"), &playlistId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "playlistId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadPlaylistCover(w, r, playlistId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Restore operation middleware
func (siw *ServerInterfaceWrapper) Restore(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Restore(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRestoreStatus operation middleware
func (siw *ServerInterfaceWrapper) GetRestoreStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "restoreId" -------------
	var restoreId string

	err = runtime.BindStyledParameterWithOptions("simple", "restoreId", chi.URLParam(r, "restoreId"), &restoreId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "restoreId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRestoreStatus(w, r, restoreId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTracks operation middleware
func (siw *ServerInterfaceWrapper) GetTracks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTracks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadTrack operation middleware
func (siw *ServerInterfaceWrapper) UploadTrack(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadTrack(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamTrack operation middleware
func (siw *ServerInterfaceWrapper) StreamTrack(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamTrackParams

	// ------------- Optional query parameter "quality" -------------

	err = runtime.BindQueryParameter("form", true, false, "quality", r.URL.Query(), &params.Quality)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quality", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamTrack(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StreamTrackHead operation middleware
func (siw *ServerInterfaceWrapper) StreamTrackHead(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int32

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params StreamTrackHeadParams

	// ------------- Optional query parameter "quality" -------------

	err = runtime.BindQueryParameter("form", true, false, "quality", r.URL.Query(), &params.Quality)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "quality", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StreamTrackHead(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTrack operation middleware
func (siw *ServerInterfaceWrapper) DeleteTrack(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "trackId" -------------
	var trackId int32

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTrack(w, r, trackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrackMeta operation middleware
func (siw *ServerInterfaceWrapper) GetTrackMeta(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "trackId" -------------
	var trackId int32

	err = runtime.BindStyledParameterWithOptions("simple", "trackId", chi.URLParam(r, "trackId"), &trackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "trackId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrackMeta(w, r, trackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserById operation middleware
func (siw *ServerInterfaceWrapper) GetUserById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserById(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangeUser operation middleware
func (siw *ServerInterfaceWrapper) ChangeUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangeUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserAvatar(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) GetUserAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserAvatar(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadUserAvatar operation middleware
func (siw *ServerInterfaceWrapper) UploadUserAvatar(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadUserAvatar(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId int32

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/albums", wrapper.CreateAlbum)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/albums/{albumId}", wrapper.DeleteAlbum)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/albums/{albumId}", wrapper.GetAlbum)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/albums/{albumId}/cover", wrapper.DeleteAlbumCover)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/albums/{albumId}/cover", wrapper.GetAlbumCover)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/albums/{albumId}/cover", wrapper.UploadAlbumCover)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/artists", wrapper.GetAllArtists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/artists", wrapper.CreateArtist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/artists/{artistId}", wrapper.DeleteArtist)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/artists/{artistId}", wrapper.GetArtist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/artists/{artistId}/image", wrapper.DeleteArtistImage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/artists/{artistId}/image", wrapper.GetArtistImage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/artists/{artistId}/image", wrapper.UploadArtistImage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/backup", wrapper.Backup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ping", wrapper.Ping)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/playlists", wrapper.GetPlaylists)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/playlists", wrapper.CreatePlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/playlists/{playlistId}", wrapper.DeletePlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/playlists/{playlistId}", wrapper.GetPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/playlists/{playlistId}", wrapper.UpdatePlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/playlists/{playlistId}", wrapper.AddTrackToPlaylist)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/playlists/{playlistId}/cover", wrapper.DeletePlaylistCover)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/playlists/{playlistId}/cover", wrapper.GetPlaylistCover)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/playlists/{playlistId}/cover", wrapper.UploadPlaylistCover)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/restore", wrapper.Restore)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/restore/{restoreId}", wrapper.GetRestoreStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tracks", wrapper.GetTracks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/tracks", wrapper.UploadTrack)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tracks/{id}/stream", wrapper.StreamTrack)
	})
	r.Group(func(r chi.Router) {
		r.Head(options.BaseURL+"/tracks/{id}/stream", wrapper.StreamTrackHead)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/tracks/{trackId}", wrapper.DeleteTrack)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tracks/{trackId}", wrapper.GetTrackMeta)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{userId}", wrapper.GetUserById)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/users/{userId}", wrapper.ChangeUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/users/{userId}/avatar", wrapper.DeleteUserAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{userId}/avatar", wrapper.GetUserAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/{userId}/avatar", wrapper.UploadUserAvatar)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/users/{userId}/change_password", wrapper.ChangePassword)
	})

	return r
}
