"""add new field to Track entity

Revision ID: 0829a7b38fbf
Revises: 8140d53af61b
Create Date: 2025-06-06 17:44:42.518982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0829a7b38fbf'
down_revision: Union[str, None] = '8140d53af61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'url')
    # ### end Alembic commands ###
