"""add unique constraint on artist name

Revision ID: 2c567dacbd26
Revises: ee0692b7d979
Create Date: 2025-06-06 22:18:38.243201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c567dacbd26'
down_revision: Union[str, None] = 'ee0692b7d979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artist', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist', type_='unique')
    # ### end Alembic commands ###
