"""add needed ForeignKey

Revision ID: 8140d53af61b
Revises: 45edf67cbbad
Create Date: 2025-06-05 21:01:02.570759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8140d53af61b'
down_revision: Union[str, None] = '45edf67cbbad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('album_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'track', 'album', ['album_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track', type_='foreignkey')
    op.drop_column('track', 'album_id')
    # ### end Alembic commands ###
