"""add unique contraint to track.url field

Revision ID: ee0692b7d979
Revises: 0829a7b38fbf
Create Date: 2025-06-06 20:35:12.681220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0692b7d979'
down_revision: Union[str, None] = '0829a7b38fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'track', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'track', type_='unique')
    # ### end Alembic commands ###
