// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add_to_queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToTranscodingQueue = `-- name: AddToTranscodingQueue :one
INSERT INTO public."transcoding_queue" (track_original_file_name, track_id, was_failed, error_msg)
    VALUES ($1, $2, $3, $4)
    RETURNING id, added_at, track_original_file_name, track_id, was_failed, error_msg
`

type AddToTranscodingQueueParams struct {
	TrackOriginalFileName string
	TrackID               int32
	WasFailed             bool
	ErrorMsg              pgtype.Text
}

func (q *Queries) AddToTranscodingQueue(ctx context.Context, arg AddToTranscodingQueueParams) (TranscodingQueue, error) {
	row := q.db.QueryRow(ctx, addToTranscodingQueue,
		arg.TrackOriginalFileName,
		arg.TrackID,
		arg.WasFailed,
		arg.ErrorMsg,
	)
	var i TranscodingQueue
	err := row.Scan(
		&i.ID,
		&i.AddedAt,
		&i.TrackOriginalFileName,
		&i.TrackID,
		&i.WasFailed,
		&i.ErrorMsg,
	)
	return i, err
}
