// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add_track_to_album.sql

package db

import (
	"context"
)

const addTrackToAlbum = `-- name: AddTrackToAlbum :exec
INSERT INTO "track_album" (track_id, album_id)
    VALUES ($1, $2)
`

type AddTrackToAlbumParams struct {
	TrackID int32
	AlbumID int32
}

func (q *Queries) AddTrackToAlbum(ctx context.Context, arg AddTrackToAlbumParams) error {
	_, err := q.db.Exec(ctx, addTrackToAlbum, arg.TrackID, arg.AlbumID)
	return err
}
