// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add_presets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTrackPresets = `-- name: AddTrackPresets :one
UPDATE "track" SET
    fast_preset_fname = $2,
    standard_preset_fname = $3,
    high_preset_fname = $4,
    lossless_preset_fname = $5
WHERE id = $1
RETURNING id, name, duration, fast_preset_fname, standard_preset_fname, high_preset_fname, lossless_preset_fname, artist_id
`

type AddTrackPresetsParams struct {
	ID                  int32
	FastPresetFname     pgtype.Text
	StandardPresetFname pgtype.Text
	HighPresetFname     pgtype.Text
	LosslessPresetFname pgtype.Text
}

func (q *Queries) AddTrackPresets(ctx context.Context, arg AddTrackPresetsParams) (Track, error) {
	row := q.db.QueryRow(ctx, addTrackPresets,
		arg.ID,
		arg.FastPresetFname,
		arg.StandardPresetFname,
		arg.HighPresetFname,
		arg.LosslessPresetFname,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Duration,
		&i.FastPresetFname,
		&i.StandardPresetFname,
		&i.HighPresetFname,
		&i.LosslessPresetFname,
		&i.ArtistID,
	)
	return i, err
}
