// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add_presets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPostTranscodingInfo = `-- name: AddPostTranscodingInfo :one
UPDATE "track" SET
    duration_ms = $2,
    fast_preset_fname = $3,
    standard_preset_fname = $4,
    high_preset_fname = $5,
    lossless_preset_fname = $6
WHERE id = $1
RETURNING id, name, duration_ms, url, fast_preset_fname, standard_preset_fname, high_preset_fname, lossless_preset_fname, is_globally_available, artist_id, upload_by_user
`

type AddPostTranscodingInfoParams struct {
	ID                  int32
	DurationMs          pgtype.Int4
	FastPresetFname     pgtype.Text
	StandardPresetFname pgtype.Text
	HighPresetFname     pgtype.Text
	LosslessPresetFname pgtype.Text
}

func (q *Queries) AddPostTranscodingInfo(ctx context.Context, arg AddPostTranscodingInfoParams) (Track, error) {
	row := q.db.QueryRow(ctx, addPostTranscodingInfo,
		arg.ID,
		arg.DurationMs,
		arg.FastPresetFname,
		arg.StandardPresetFname,
		arg.HighPresetFname,
		arg.LosslessPresetFname,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationMs,
		&i.Url,
		&i.FastPresetFname,
		&i.StandardPresetFname,
		&i.HighPresetFname,
		&i.LosslessPresetFname,
		&i.IsGloballyAvailable,
		&i.ArtistID,
		&i.UploadByUser,
	)
	return i, err
}
