// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add_track_to_playlist.sql

package db

import (
	"context"
)

const addTrackToPlaylist = `-- name: AddTrackToPlaylist :exec
INSERT INTO "track_playlist" (track_id, playlist_id)
    VALUES ($1, $2)
`

type AddTrackToPlaylistParams struct {
	TrackID    int32
	PlaylistID int32
}

func (q *Queries) AddTrackToPlaylist(ctx context.Context, arg AddTrackToPlaylistParams) error {
	_, err := q.db.Exec(ctx, addTrackToPlaylist, arg.TrackID, arg.PlaylistID)
	return err
}
