// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clear_backup_data.sql

package db

import (
	"context"
)

const clearBackupData = `-- name: ClearBackupData :exec
TRUNCATE TABLE
    public."track_playlist",
    public."track_album",
    public."transcoding_queue",
    public."track",
    public."playlist",
    public."album",
    public."artist",
    public."user"
RESTART IDENTITY CASCADE
`

func (q *Queries) ClearBackupData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearBackupData)
	return err
}
