// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: confirm_successfull_backup.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmBackup = `-- name: ConfirmBackup :exec
UPDATE public."backup_status" SET
    status = 'finished',
    error = NULL,
    finished_at = now(),
    archive_path = $2,
    size_bytes = $3
WHERE id = $1
`

type ConfirmBackupParams struct {
	ID          string
	ArchivePath pgtype.Text
	SizeBytes   pgtype.Int8
}

func (q *Queries) ConfirmBackup(ctx context.Context, arg ConfirmBackupParams) error {
	_, err := q.db.Exec(ctx, confirmBackup, arg.ID, arg.ArchivePath, arg.SizeBytes)
	return err
}
