// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: confirm_errornous_backup.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const errorBackup = `-- name: ErrorBackup :exec
UPDATE public."backup_status" SET
    status = 'error',
    error = $2,
    finished_at = now()
WHERE id = $1
`

type ErrorBackupParams struct {
	ID    string
	Error pgtype.Text
}

func (q *Queries) ErrorBackup(ctx context.Context, arg ErrorBackupParams) error {
	_, err := q.db.Exec(ctx, errorBackup, arg.ID, arg.Error)
	return err
}
