// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: confirm_successfull_restoring.sql

package db

import (
	"context"
)

const confirmRestoring = `-- name: ConfirmRestoring :exec
UPDATE public."restore_status" SET
    status = 'finished',
    finished_at = now()
`

func (q *Queries) ConfirmRestoring(ctx context.Context) error {
	_, err := q.db.Exec(ctx, confirmRestoring)
	return err
}
