// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: confirm_errornous_restore.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const errorRestoring = `-- name: ErrorRestoring :exec
UPDATE public."restore_status" SET
    status = 'error',
    error = $1
`

func (q *Queries) ErrorRestoring(ctx context.Context, error pgtype.Text) error {
	_, err := q.db.Exec(ctx, errorRestoring, error)
	return err
}
