// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO "album" (name, artist_id, release_year, release_full_date)
    VALUES ($1, $2, $3, $4)
    RETURNING id, name, release_year, release_full_date, artist_id
`

type CreateAlbumParams struct {
	Name            string
	ArtistID        int32
	ReleaseYear     pgtype.Int4
	ReleaseFullDate pgtype.Date
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.Name,
		arg.ArtistID,
		arg.ReleaseYear,
		arg.ReleaseFullDate,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ReleaseYear,
		&i.ReleaseFullDate,
		&i.ArtistID,
	)
	return i, err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO "artist" (name)
values ($1)
RETURNING id, name, url
`

func (q *Queries) CreateArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name, &i.Url)
	return i, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT into "playlist" (name, owner_id, is_public)
VALUES ($1, $2, $3)
RETURNING id, name, is_public, owner_id
`

type CreatePlaylistParams struct {
	Name     string
	OwnerID  int32
	IsPublic bool
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist, arg.Name, arg.OwnerID, arg.IsPublic)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPublic,
		&i.OwnerID,
	)
	return i, err
}

const createTrack = `-- name: CreateTrack :one
INSERT INTO "track" (name, artist_id, upload_by_user, is_globally_available)
    VALUES ($1, $2, $3, $4)
RETURNING id, name, duration_ms, url, fast_preset_fname, standard_preset_fname, high_preset_fname, lossless_preset_fname, is_globally_available, artist_id, upload_by_user
`

type CreateTrackParams struct {
	Name                string
	ArtistID            int32
	UploadByUser        pgtype.Int4
	IsGloballyAvailable bool
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack,
		arg.Name,
		arg.ArtistID,
		arg.UploadByUser,
		arg.IsGloballyAvailable,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DurationMs,
		&i.Url,
		&i.FastPresetFname,
		&i.StandardPresetFname,
		&i.HighPresetFname,
		&i.LosslessPresetFname,
		&i.IsGloballyAvailable,
		&i.ArtistID,
		&i.UploadByUser,
	)
	return i, err
}
