// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (
    username, email, password, salt,
    password_memory, password_iterations, password_parallelism, password_key_length,
    is_superuser, created_at, updated_at
)
values (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, now(), now()
)
RETURNING id, username, is_superuser, email, password, salt, password_memory, password_iterations, password_parallelism, password_key_length, refresh_version, created_at, updated_at
`

type CreateUserParams struct {
	Username            string
	Email               pgtype.Text
	Password            []byte
	Salt                []byte
	PasswordMemory      int32
	PasswordIterations  int32
	PasswordParallelism int32
	PasswordKeyLength   int32
	IsSuperuser         bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Salt,
		arg.PasswordMemory,
		arg.PasswordIterations,
		arg.PasswordParallelism,
		arg.PasswordKeyLength,
		arg.IsSuperuser,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IsSuperuser,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.PasswordMemory,
		&i.PasswordIterations,
		&i.PasswordParallelism,
		&i.PasswordKeyLength,
		&i.RefreshVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
