// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO "album" (name, artist_id)
    VALUES ($1, $2)
    RETURNING id, name, artist_id
`

type CreateAlbumParams struct {
	Name     string
	ArtistID int32
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum, arg.Name, arg.ArtistID)
	var i Album
	err := row.Scan(&i.ID, &i.Name, &i.ArtistID)
	return i, err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO "artist" (name)
values ($1)
RETURNING id, name
`

func (q *Queries) CreateArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRow(ctx, createArtist, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createPlaylist = `-- name: CreatePlaylist :one
INSERT into "playlist" (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id
`

type CreatePlaylistParams struct {
	Name    string
	OwnerID pgtype.Int4
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, createPlaylist, arg.Name, arg.OwnerID)
	var i Playlist
	err := row.Scan(&i.ID, &i.Name, &i.OwnerID)
	return i, err
}

const createTrack = `-- name: CreateTrack :one
INSERT INTO "track" (name, artist_id, duration)
    VALUES ($1, $2, $3)
RETURNING id, name, duration, artist_id
`

type CreateTrackParams struct {
	Name     string
	ArtistID int32
	Duration pgtype.Int4
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack, arg.Name, arg.ArtistID, arg.Duration)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Duration,
		&i.ArtistID,
	)
	return i, err
}
