// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_from_queue.sql

package db

import (
	"context"
)

const deleteFromTranscodingQueue = `-- name: DeleteFromTranscodingQueue :one
DELETE FROM public."transcoding_queue"
    WHERE id = $1
    RETURNING id, added_at, track_original_file_name, track_id, was_failed, error_msg
`

func (q *Queries) DeleteFromTranscodingQueue(ctx context.Context, id int64) (TranscodingQueue, error) {
	row := q.db.QueryRow(ctx, deleteFromTranscodingQueue, id)
	var i TranscodingQueue
	err := row.Scan(
		&i.ID,
		&i.AddedAt,
		&i.TrackOriginalFileName,
		&i.TrackID,
		&i.WasFailed,
		&i.ErrorMsg,
	)
	return i, err
}
