// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_password_reset_code.sql

package db

import (
	"context"
)

const deletePasswordResetCodeByUserID = `-- name: DeletePasswordResetCodeByUserID :exec
DELETE FROM "password_reset_code"
WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetCodeByUserID(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deletePasswordResetCodeByUserID, userID)
	return err
}
