// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_track_from_playlist.sql

package db

import (
	"context"
)

const deleteTrackFromPlaylist = `-- name: DeleteTrackFromPlaylist :exec
DELETE FROM "track_playlist"
    WHERE track_id = $1
`

func (q *Queries) DeleteTrackFromPlaylist(ctx context.Context, trackID int32) error {
	_, err := q.db.Exec(ctx, deleteTrackFromPlaylist, trackID)
	return err
}

const deleteTrackFromPlaylistRelation = `-- name: DeleteTrackFromPlaylistRelation :exec
DELETE FROM "track_playlist"
    WHERE playlist_id = $1
        AND track_id = $2
`

type DeleteTrackFromPlaylistRelationParams struct {
	PlaylistID int32
	TrackID    int32
}

func (q *Queries) DeleteTrackFromPlaylistRelation(ctx context.Context, arg DeleteTrackFromPlaylistRelationParams) error {
	_, err := q.db.Exec(ctx, deleteTrackFromPlaylistRelation, arg.PlaylistID, arg.TrackID)
	return err
}
