// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete.sql

package db

import (
	"context"
)

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE from "album"
    where id = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAlbum, id)
	return err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM "artist" 
    where id = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteArtist, id)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE from "playlist"
    where id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePlaylist, id)
	return err
}

const deleteTrack = `-- name: DeleteTrack :exec
DELETE from "track"
    where id = $1
`

func (q *Queries) DeleteTrack(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTrack, id)
	return err
}
