// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_track_from_album.sql

package db

import (
	"context"
)

const deleteTrackFromAlbum = `-- name: DeleteTrackFromAlbum :exec
DELETE FROM "track_album"
    WHERE track_id = $1
`

func (q *Queries) DeleteTrackFromAlbum(ctx context.Context, trackID int32) error {
	_, err := q.db.Exec(ctx, deleteTrackFromAlbum, trackID)
	return err
}
