// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: find_playlist_by_user_and_name.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findUsersPlaylistByName = `-- name: FindUsersPlaylistByName :one
SELECT p.id FROM playlist as p
    WHERE p.owner_id = $1 AND p.name = $2
`

type FindUsersPlaylistByNameParams struct {
	OwnerID pgtype.Int4
	Name    string
}

func (q *Queries) FindUsersPlaylistByName(ctx context.Context, arg FindUsersPlaylistByNameParams) (int32, error) {
	row := q.db.QueryRow(ctx, findUsersPlaylistByName, arg.OwnerID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}
