// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: find_user_by_email.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, salt, is_superuser, refresh_version
FROM "user"
WHERE LOWER(email) = LOWER($1)
`

type GetUserByEmailRow struct {
	ID             int32
	Username       string
	Email          pgtype.Text
	Password       []byte
	Salt           []byte
	IsSuperuser    bool
	RefreshVersion int32
}

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.IsSuperuser,
		&i.RefreshVersion,
	)
	return i, err
}
