// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: find_user_by_username.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, salt, is_superuser
FROM "user"
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID          int32
	Username    string
	Email       pgtype.Text
	Password    []byte
	Salt        []byte
	IsSuperuser bool
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.IsSuperuser,
	)
	return i, err
}
