// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: find_user_by_username.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, salt,
    password_memory, password_iterations, password_parallelism, password_key_length,
    is_superuser, refresh_version
FROM "user"
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID                  int32
	Username            string
	Email               pgtype.Text
	Password            []byte
	Salt                []byte
	PasswordMemory      int32
	PasswordIterations  int32
	PasswordParallelism int32
	PasswordKeyLength   int32
	IsSuperuser         bool
	RefreshVersion      int32
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.PasswordMemory,
		&i.PasswordIterations,
		&i.PasswordParallelism,
		&i.PasswordKeyLength,
		&i.IsSuperuser,
		&i.RefreshVersion,
	)
	return i, err
}
