// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: find_user_by_id.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password, salt,
    password_memory, password_iterations, password_parallelism, password_key_length,
    is_superuser, refresh_version
FROM "user"
WHERE id = $1
`

type GetUserByIDRow struct {
	ID                  int32
	Username            string
	Email               pgtype.Text
	Password            []byte
	Salt                []byte
	PasswordMemory      int32
	PasswordIterations  int32
	PasswordParallelism int32
	PasswordKeyLength   int32
	IsSuperuser         bool
	RefreshVersion      int32
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.PasswordMemory,
		&i.PasswordIterations,
		&i.PasswordParallelism,
		&i.PasswordKeyLength,
		&i.IsSuperuser,
		&i.RefreshVersion,
	)
	return i, err
}
