// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const canUserAccessTrack = `-- name: CanUserAccessTrack :one
SELECT EXISTS (
    SELECT 1
    FROM "track" AS t
    WHERE t.id = $1::integer
        AND (
            t.is_globally_available
            OR t.upload_by_user = $2::integer
            OR EXISTS (
                SELECT 1
                FROM "track_playlist" AS tp
                INNER JOIN "playlist" AS p
                    ON p.id = tp.playlist_id
                LEFT JOIN "playlist_share_info" AS psi
                    ON psi.playlist_id = p.id
                    AND psi.shared_with_user = $2::integer
                WHERE tp.track_id = t.id
                    AND (
                        p.owner_id = $2::integer
                        OR p.is_public IS TRUE
                        OR psi.shared_with_user IS NOT NULL
                    )
            )
        )
)::boolean
`

type CanUserAccessTrackParams struct {
	TrackID int32
	UserID  int32
}

func (q *Queries) CanUserAccessTrack(ctx context.Context, arg CanUserAccessTrackParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserAccessTrack, arg.TrackID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getAlbum = `-- name: GetAlbum :one
SELECT id , name, release_year, release_full_date
    FROM "album" 
WHERE "album".id = $1
`

type GetAlbumRow struct {
	ID              int32
	Name            string
	ReleaseYear     pgtype.Int4
	ReleaseFullDate pgtype.Date
}

func (q *Queries) GetAlbum(ctx context.Context, id int32) (GetAlbumRow, error) {
	row := q.db.QueryRow(ctx, getAlbum, id)
	var i GetAlbumRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ReleaseYear,
		&i.ReleaseFullDate,
	)
	return i, err
}

const getAlbumByTrackID = `-- name: GetAlbumByTrackID :one
SELECT album_id FROM track_album
    WHERE track_id = $1
    LIMIT 1
`

func (q *Queries) GetAlbumByTrackID(ctx context.Context, trackID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getAlbumByTrackID, trackID)
	var album_id int32
	err := row.Scan(&album_id)
	return album_id, err
}

const getAlbumWithTracks = `-- name: GetAlbumWithTracks :many
SELECT "album".id, "album".name, "album".release_year,
        "album".release_full_date, "track_album".track_id
    FROM "album" INNER JOIN "track_album"
    ON "album".id = "track_album".album_id
WHERE "album".id = $1
`

type GetAlbumWithTracksRow struct {
	ID              int32
	Name            string
	ReleaseYear     pgtype.Int4
	ReleaseFullDate pgtype.Date
	TrackID         int32
}

func (q *Queries) GetAlbumWithTracks(ctx context.Context, id int32) ([]GetAlbumWithTracksRow, error) {
	rows, err := q.db.Query(ctx, getAlbumWithTracks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumWithTracksRow
	for rows.Next() {
		var i GetAlbumWithTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ReleaseYear,
			&i.ReleaseFullDate,
			&i.TrackID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllArtists = `-- name: GetAllArtists :many
SELECT "id", "name" FROM artist
`

type GetAllArtistsRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetAllArtists(ctx context.Context) ([]GetAllArtistsRow, error) {
	rows, err := q.db.Query(ctx, getAllArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllArtistsRow
	for rows.Next() {
		var i GetAllArtistsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTracks = `-- name: GetAllTracks :many
SELECT t.id, t.name, t.artist_id, duration_ms,
t.fast_preset_fname, t.standard_preset_fname,
t.high_preset_fname, t.lossless_preset_fname
    FROM "track" AS t
`

type GetAllTracksRow struct {
	ID                  int32
	Name                string
	ArtistID            int32
	DurationMs          pgtype.Int4
	FastPresetFname     pgtype.Text
	StandardPresetFname pgtype.Text
	HighPresetFname     pgtype.Text
	LosslessPresetFname pgtype.Text
}

func (q *Queries) GetAllTracks(ctx context.Context) ([]GetAllTracksRow, error) {
	rows, err := q.db.Query(ctx, getAllTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTracksRow
	for rows.Next() {
		var i GetAllTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ArtistID,
			&i.DurationMs,
			&i.FastPresetFname,
			&i.StandardPresetFname,
			&i.HighPresetFname,
			&i.LosslessPresetFname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsernames = `-- name: GetAllUsernames :many
SELECT id, username FROM "user"
`

type GetAllUsernamesRow struct {
	ID       int32
	Username string
}

func (q *Queries) GetAllUsernames(ctx context.Context) ([]GetAllUsernamesRow, error) {
	rows, err := q.db.Query(ctx, getAllUsernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsernamesRow
	for rows.Next() {
		var i GetAllUsernamesRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsernamesExcept = `-- name: GetAllUsernamesExcept :many
SELECT id, username FROM "user"
WHERE id <> $1
`

type GetAllUsernamesExceptRow struct {
	ID       int32
	Username string
}

func (q *Queries) GetAllUsernamesExcept(ctx context.Context, id int32) ([]GetAllUsernamesExceptRow, error) {
	rows, err := q.db.Query(ctx, getAllUsernamesExcept, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsernamesExceptRow
	for rows.Next() {
		var i GetAllUsernamesExceptRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtist = `-- name: GetArtist :one
SELECT "artist".id, "artist".name
    from "artist" 
where "artist".id = $1
`

type GetArtistRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetArtist(ctx context.Context, id int32) (GetArtistRow, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i GetArtistRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getArtistWithAlbums = `-- name: GetArtistWithAlbums :many
SELECT "artist".id as artist_id, "artist".name as artist_name,
        "album".id as album_id
    FROM "artist" INNER JOIN "album"
    ON "artist".id = "album".artist_id
WHERE "artist".id = $1
`

type GetArtistWithAlbumsRow struct {
	ArtistID   int32
	ArtistName string
	AlbumID    int32
}

func (q *Queries) GetArtistWithAlbums(ctx context.Context, id int32) ([]GetArtistWithAlbumsRow, error) {
	rows, err := q.db.Query(ctx, getArtistWithAlbums, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtistWithAlbumsRow
	for rows.Next() {
		var i GetArtistWithAlbumsRow
		if err := rows.Scan(&i.ArtistID, &i.ArtistName, &i.AlbumID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistsWithFilter = `-- name: GetArtistsWithFilter :many
SELECT "id", "name" FROM artist
                    -- starts with
    WHERE "name" LIKE $1 || '%'
LIMIT $2
`

type GetArtistsWithFilterParams struct {
	Column1 pgtype.Text
	Limit   int32
}

type GetArtistsWithFilterRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetArtistsWithFilter(ctx context.Context, arg GetArtistsWithFilterParams) ([]GetArtistsWithFilterRow, error) {
	rows, err := q.db.Query(ctx, getArtistsWithFilter, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtistsWithFilterRow
	for rows.Next() {
		var i GetArtistsWithFilterRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT id, name, owner_id
    FROM "playlist"
WHERE "playlist".id = $1
`

type GetPlaylistRow struct {
	ID      int32
	Name    string
	OwnerID int32
}

func (q *Queries) GetPlaylist(ctx context.Context, id int32) (GetPlaylistRow, error) {
	row := q.db.QueryRow(ctx, getPlaylist, id)
	var i GetPlaylistRow
	err := row.Scan(&i.ID, &i.Name, &i.OwnerID)
	return i, err
}

const getPlaylistWithTracks = `-- name: GetPlaylistWithTracks :many
SELECT "playlist".id, "playlist".name, "track_playlist".track_id
    from "playlist" inner join "track_playlist"
    ON "playlist".id = "track_playlist".playlist_id
    WHERE "playlist".id = $1
`

type GetPlaylistWithTracksRow struct {
	ID      int32
	Name    string
	TrackID int32
}

func (q *Queries) GetPlaylistWithTracks(ctx context.Context, id int32) ([]GetPlaylistWithTracksRow, error) {
	rows, err := q.db.Query(ctx, getPlaylistWithTracks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlaylistWithTracksRow
	for rows.Next() {
		var i GetPlaylistWithTracksRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TrackID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicPlaylists = `-- name: GetPublicPlaylists :many
SELECT p.id, p.name, p.owner_id
    FROM "playlist" p
    WHERE p.is_public IS TRUE AND 
        p.owner_id <> $1
`

type GetPublicPlaylistsRow struct {
	ID      int32
	Name    string
	OwnerID int32
}

func (q *Queries) GetPublicPlaylists(ctx context.Context, ownerID int32) ([]GetPublicPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, getPublicPlaylists, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicPlaylistsRow
	for rows.Next() {
		var i GetPublicPlaylistsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedPlaylists = `-- name: GetSharedPlaylists :many
SELECT p.id, p.name, p.owner_id, ps.has_write_permission
    FROM "playlist" p INNER JOIN "playlist_share_info" ps
        ON p.id = ps.playlist_id
    WHERE ps.shared_with_user = $1
`

type GetSharedPlaylistsRow struct {
	ID                 int32
	Name               string
	OwnerID            int32
	HasWritePermission bool
}

func (q *Queries) GetSharedPlaylists(ctx context.Context, sharedWithUser int32) ([]GetSharedPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, getSharedPlaylists, sharedWithUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSharedPlaylistsRow
	for rows.Next() {
		var i GetSharedPlaylistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.HasWritePermission,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrack = `-- name: GetTrack :one
SELECT t.id, t.name, t.artist_id, a.name AS artist_name, ta.album_id, t.duration_ms,
t.fast_preset_fname, t.standard_preset_fname,
t.high_preset_fname, t.lossless_preset_fname,
t.is_globally_available, t.upload_by_user
    FROM "track" AS t
    INNER JOIN "track_album" AS ta
        ON t.id = ta.track_id
    INNER JOIN "artist" AS a
        ON t.artist_id = a.id
    WHERE t.id = $1
    LIMIT 1
`

type GetTrackRow struct {
	ID                  int32
	Name                string
	ArtistID            int32
	ArtistName          string
	AlbumID             int32
	DurationMs          pgtype.Int4
	FastPresetFname     pgtype.Text
	StandardPresetFname pgtype.Text
	HighPresetFname     pgtype.Text
	LosslessPresetFname pgtype.Text
	IsGloballyAvailable bool
	UploadByUser        pgtype.Int4
}

func (q *Queries) GetTrack(ctx context.Context, id int32) (GetTrackRow, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i GetTrackRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ArtistID,
		&i.ArtistName,
		&i.AlbumID,
		&i.DurationMs,
		&i.FastPresetFname,
		&i.StandardPresetFname,
		&i.HighPresetFname,
		&i.LosslessPresetFname,
		&i.IsGloballyAvailable,
		&i.UploadByUser,
	)
	return i, err
}

const getUserOwnedPlaylists = `-- name: GetUserOwnedPlaylists :many
SELECT "playlist".id, "playlist".name
    FROM "playlist"
    WHERE "playlist".owner_id = $1
`

type GetUserOwnedPlaylistsRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetUserOwnedPlaylists(ctx context.Context, ownerID int32) ([]GetUserOwnedPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, getUserOwnedPlaylists, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOwnedPlaylistsRow
	for rows.Next() {
		var i GetUserOwnedPlaylistsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTracks = `-- name: GetUserTracks :many
SELECT DISTINCT t.id, t.name, t.artist_id, duration_ms,
t.fast_preset_fname, t.standard_preset_fname,
t.high_preset_fname, t.lossless_preset_fname
    FROM "track" AS t
    WHERE t.is_globally_available
        OR t.upload_by_user = $1::integer
        OR EXISTS (
            SELECT 1
            FROM "track_playlist" AS tp
            INNER JOIN "playlist" AS p
                ON p.id = tp.playlist_id
            LEFT JOIN "playlist_share_info" AS psi
                ON psi.playlist_id = p.id
                AND psi.shared_with_user = $1::integer
            WHERE tp.track_id = t.id
                AND (
                    p.owner_id = $1::integer
                    OR p.is_public IS TRUE
                    OR psi.shared_with_user IS NOT NULL
                )
        )
`

type GetUserTracksRow struct {
	ID                  int32
	Name                string
	ArtistID            int32
	DurationMs          pgtype.Int4
	FastPresetFname     pgtype.Text
	StandardPresetFname pgtype.Text
	HighPresetFname     pgtype.Text
	LosslessPresetFname pgtype.Text
}

func (q *Queries) GetUserTracks(ctx context.Context, userID int32) ([]GetUserTracksRow, error) {
	rows, err := q.db.Query(ctx, getUserTracks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTracksRow
	for rows.Next() {
		var i GetUserTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ArtistID,
			&i.DurationMs,
			&i.FastPresetFname,
			&i.StandardPresetFname,
			&i.HighPresetFname,
			&i.LosslessPresetFname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsername = `-- name: GetUsername :one
SELECT id, username FROM "user"
WHERE id = $1
`

type GetUsernameRow struct {
	ID       int32
	Username string
}

func (q *Queries) GetUsername(ctx context.Context, id int32) (GetUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUsername, id)
	var i GetUsernameRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const getUsersPlaylistByName = `-- name: GetUsersPlaylistByName :one
SELECT p.id FROM "playlist" as p
    WHERE p.owner_id = $1 AND p.name = $2
`

type GetUsersPlaylistByNameParams struct {
	OwnerID int32
	Name    string
}

func (q *Queries) GetUsersPlaylistByName(ctx context.Context, arg GetUsersPlaylistByNameParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUsersPlaylistByName, arg.OwnerID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const userCanReadPlaylist = `-- name: UserCanReadPlaylist :one
SELECT EXISTS (
    SELECT 1
    FROM "playlist" AS p
    LEFT JOIN "playlist_share_info" AS ps
        ON ps.playlist_id = p.id
        AND ps.shared_with_user = $1::integer
    WHERE p.id = $2::integer
        AND (
            p.owner_id = $1::integer
            OR p.is_public IS TRUE
            OR ps.shared_with_user IS NOT NULL
        )
)::boolean
`

type UserCanReadPlaylistParams struct {
	UserID     int32
	PlaylistID int32
}

func (q *Queries) UserCanReadPlaylist(ctx context.Context, arg UserCanReadPlaylistParams) (bool, error) {
	row := q.db.QueryRow(ctx, userCanReadPlaylist, arg.UserID, arg.PlaylistID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const userCanWritePlaylist = `-- name: UserCanWritePlaylist :one
SELECT EXISTS (
    SELECT 1
    FROM "playlist" AS p
    LEFT JOIN "playlist_share_info" AS ps
        ON ps.playlist_id = p.id
        AND ps.shared_with_user = $1::integer
    WHERE p.id = $2::integer
        AND (
            p.owner_id = $1::integer
            OR ps.has_write_permission IS TRUE
        )
)::boolean
`

type UserCanWritePlaylistParams struct {
	UserID     int32
	PlaylistID int32
}

func (q *Queries) UserCanWritePlaylist(ctx context.Context, arg UserCanWritePlaylistParams) (bool, error) {
	row := q.db.QueryRow(ctx, userCanWritePlaylist, arg.UserID, arg.PlaylistID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
