// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get.sql

package db

import (
	"context"
)

const getAlbum = `-- name: GetAlbum :one
SELECT "album".id as id, "album".name as name
    from "album" 
WHERE "album".id = $1
`

type GetAlbumRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetAlbum(ctx context.Context, id int32) (GetAlbumRow, error) {
	row := q.db.QueryRow(ctx, getAlbum, id)
	var i GetAlbumRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getArtist = `-- name: GetArtist :one
SELECT "artist".id, "artist".name
    from "artist" 
where "artist".id = $1
`

func (q *Queries) GetArtist(ctx context.Context, id int32) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtist, id)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPlaylist = `-- name: GetPlaylist :many
SELECT "playlist".id, "playlist".name, "track_playlist".track_id
    from "playlist" inner join "track_playlist"
    ON "playlist".id = "track_playlist".playlist_id
`

type GetPlaylistRow struct {
	ID      int32
	Name    string
	TrackID int32
}

func (q *Queries) GetPlaylist(ctx context.Context) ([]GetPlaylistRow, error) {
	rows, err := q.db.Query(ctx, getPlaylist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlaylistRow
	for rows.Next() {
		var i GetPlaylistRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TrackID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrack = `-- name: GetTrack :one
SELECT id, name, duration, artist_id FROM "track"
    WHERE id = $1
`

func (q *Queries) GetTrack(ctx context.Context, id int32) (Track, error) {
	row := q.db.QueryRow(ctx, getTrack, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Duration,
		&i.ArtistID,
	)
	return i, err
}
