// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_all.sql

package db

import (
	"context"
)

const getAllArtists = `-- name: GetAllArtists :many
SELECT "id", "name" FROM artist
`

type GetAllArtistsRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetAllArtists(ctx context.Context) ([]GetAllArtistsRow, error) {
	rows, err := q.db.Query(ctx, getAllArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllArtistsRow
	for rows.Next() {
		var i GetAllArtistsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
