// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_with_tracks.sql

package db

import (
	"context"
)

const getAlbumWithTracks = `-- name: GetAlbumWithTracks :many
SELECT "album".id, "album".name, "track_album".track_id
    from "album" inner join "track_album"
    ON "album".id = "track_album".album_id
WHERE "album".id = $1
`

type GetAlbumWithTracksRow struct {
	ID      int32
	Name    string
	TrackID int32
}

func (q *Queries) GetAlbumWithTracks(ctx context.Context, id int32) ([]GetAlbumWithTracksRow, error) {
	rows, err := q.db.Query(ctx, getAlbumWithTracks, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumWithTracksRow
	for rows.Next() {
		var i GetAlbumWithTracksRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TrackID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
