// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_users_track.sql

package db

import (
	"context"
)

const getUserTracks = `-- name: GetUserTracks :many
SELECT id, name, duration, url, fast_preset_fname, standard_preset_fname, high_preset_fname, lossless_preset_fname, is_globally_available, artist_id, upload_by_user FROM "track"
`

func (q *Queries) GetUserTracks(ctx context.Context) ([]Track, error) {
	rows, err := q.db.Query(ctx, getUserTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Duration,
			&i.Url,
			&i.FastPresetFname,
			&i.StandardPresetFname,
			&i.HighPresetFname,
			&i.LosslessPresetFname,
			&i.IsGloballyAvailable,
			&i.ArtistID,
			&i.UploadByUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
