// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_users_track.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserTracks = `-- name: GetUserTracks :many
SELECT t.id, t.name, t.artist_id,
t.fast_preset_fname, t.standard_preset_fname,
t.high_preset_fname, t.lossless_preset_fname
    FROM "track" AS t
    WHERE t.is_globally_available OR t.upload_by_user = $1
`

type GetUserTracksRow struct {
	ID                  int32
	Name                string
	ArtistID            int32
	FastPresetFname     pgtype.Text
	StandardPresetFname pgtype.Text
	HighPresetFname     pgtype.Text
	LosslessPresetFname pgtype.Text
}

func (q *Queries) GetUserTracks(ctx context.Context, uploadByUser pgtype.Int4) ([]GetUserTracksRow, error) {
	rows, err := q.db.Query(ctx, getUserTracks, uploadByUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTracksRow
	for rows.Next() {
		var i GetUserTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ArtistID,
			&i.FastPresetFname,
			&i.StandardPresetFname,
			&i.HighPresetFname,
			&i.LosslessPresetFname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
