// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_active_restore_operation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveRestoreOperation = `-- name: GetActiveRestoreOperation :one
SELECT id, status, error, created_at, finished_at
FROM public."restore_status"
WHERE status IN ('pending', 'started')
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveRestoreOperationRow struct {
	ID         string
	Status     Status
	Error      pgtype.Text
	CreatedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) GetActiveRestoreOperation(ctx context.Context) (GetActiveRestoreOperationRow, error) {
	row := q.db.QueryRow(ctx, getActiveRestoreOperation)
	var i GetActiveRestoreOperationRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
