// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_with_albums.sql

package db

import (
	"context"
)

const getArtistWithAlbums = `-- name: GetArtistWithAlbums :many
SELECT "artist".id as artist_id, "artist".name as artist_name, "album".id as album_id
    from "artist" INNER JOIN "album"
    ON "artist".id = "album".artist_id
where "artist".id = $1
`

type GetArtistWithAlbumsRow struct {
	ArtistID   int32
	ArtistName string
	AlbumID    int32
}

func (q *Queries) GetArtistWithAlbums(ctx context.Context, id int32) ([]GetArtistWithAlbumsRow, error) {
	rows, err := q.db.Query(ctx, getArtistWithAlbums, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtistWithAlbumsRow
	for rows.Next() {
		var i GetArtistWithAlbumsRow
		if err := rows.Scan(&i.ArtistID, &i.ArtistName, &i.AlbumID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
