// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_password_reset_code.sql

package db

import (
	"context"
)

const getPasswordResetCodeByUserID = `-- name: GetPasswordResetCodeByUserID :one
SELECT user_id, code_hash, expires_at, attempts_left, resend_available_at, created_at, updated_at
FROM "password_reset_code"
WHERE user_id = $1
`

func (q *Queries) GetPasswordResetCodeByUserID(ctx context.Context, userID int32) (PasswordResetCode, error) {
	row := q.db.QueryRow(ctx, getPasswordResetCodeByUserID, userID)
	var i PasswordResetCode
	err := row.Scan(
		&i.UserID,
		&i.CodeHash,
		&i.ExpiresAt,
		&i.AttemptsLeft,
		&i.ResendAvailableAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
