// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_user_playlists.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserPlaylists = `-- name: GetUserPlaylists :many
SELECT "playlist".id, "playlist".name
    FROM "playlist"
    WHERE "playlist".owner_id = $1
`

type GetUserPlaylistsRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetUserPlaylists(ctx context.Context, ownerID pgtype.Int4) ([]GetUserPlaylistsRow, error) {
	rows, err := q.db.Query(ctx, getUserPlaylists, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPlaylistsRow
	for rows.Next() {
		var i GetUserPlaylistsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
