// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_transcoding_queue_stream.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTranscodingQueue = `-- name: GetTranscodingQueue :many
SELECT id, added_at, track_original_file_name, track_id
    FROM public."transcoding_queue"
    WHERE id > $1
    ORDER BY id ASC
    LIMIT $2
`

type GetTranscodingQueueParams struct {
	ID    int32
	Limit int32
}

type GetTranscodingQueueRow struct {
	ID                    int32
	AddedAt               pgtype.Timestamp
	TrackOriginalFileName string
	TrackID               int32
}

func (q *Queries) GetTranscodingQueue(ctx context.Context, arg GetTranscodingQueueParams) ([]GetTranscodingQueueRow, error) {
	rows, err := q.db.Query(ctx, getTranscodingQueue, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTranscodingQueueRow
	for rows.Next() {
		var i GetTranscodingQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.AddedAt,
			&i.TrackOriginalFileName,
			&i.TrackID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
