// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_full_db_backup.sql

package db

import (
	"context"
)

const getAllAlbumsForBackup = `-- name: GetAllAlbumsForBackup :many
SELECT id, name, artist_id
FROM public."album"
ORDER BY id
`

type GetAllAlbumsForBackupRow struct {
	ID       int32
	Name     string
	ArtistID int32
}

func (q *Queries) GetAllAlbumsForBackup(ctx context.Context) ([]GetAllAlbumsForBackupRow, error) {
	rows, err := q.db.Query(ctx, getAllAlbumsForBackup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAlbumsForBackupRow
	for rows.Next() {
		var i GetAllAlbumsForBackupRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ArtistID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllArtistsForBackup = `-- name: GetAllArtistsForBackup :many
SELECT id, name, url
FROM public."artist"
ORDER BY id
`

func (q *Queries) GetAllArtistsForBackup(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getAllArtistsForBackup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPlaylistSharesForBackup = `-- name: GetAllPlaylistSharesForBackup :many
SELECT playlist_id, shared_with_user, has_write_permission
FROM public."playlist_share_info"
ORDER BY playlist_id, shared_with_user
`

func (q *Queries) GetAllPlaylistSharesForBackup(ctx context.Context) ([]PlaylistShareInfo, error) {
	rows, err := q.db.Query(ctx, getAllPlaylistSharesForBackup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaylistShareInfo
	for rows.Next() {
		var i PlaylistShareInfo
		if err := rows.Scan(&i.PlaylistID, &i.SharedWithUser, &i.HasWritePermission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPlaylistsForBackup = `-- name: GetAllPlaylistsForBackup :many
SELECT id, name, is_public, owner_id
FROM public."playlist"
ORDER BY id
`

func (q *Queries) GetAllPlaylistsForBackup(ctx context.Context) ([]Playlist, error) {
	rows, err := q.db.Query(ctx, getAllPlaylistsForBackup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPublic,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTrackAlbumsForBackup = `-- name: GetAllTrackAlbumsForBackup :many
SELECT track_id, album_id
FROM public."track_album"
ORDER BY track_id, album_id
`

func (q *Queries) GetAllTrackAlbumsForBackup(ctx context.Context) ([]TrackAlbum, error) {
	rows, err := q.db.Query(ctx, getAllTrackAlbumsForBackup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackAlbum
	for rows.Next() {
		var i TrackAlbum
		if err := rows.Scan(&i.TrackID, &i.AlbumID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTrackPlaylistsForBackup = `-- name: GetAllTrackPlaylistsForBackup :many
SELECT track_id, playlist_id
FROM public."track_playlist"
ORDER BY track_id, playlist_id
`

func (q *Queries) GetAllTrackPlaylistsForBackup(ctx context.Context) ([]TrackPlaylist, error) {
	rows, err := q.db.Query(ctx, getAllTrackPlaylistsForBackup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackPlaylist
	for rows.Next() {
		var i TrackPlaylist
		if err := rows.Scan(&i.TrackID, &i.PlaylistID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTracksForBackup = `-- name: GetAllTracksForBackup :many
SELECT id, name, duration_ms, url,
    fast_preset_fname, standard_preset_fname,
    high_preset_fname, lossless_preset_fname,
    is_globally_available, artist_id, upload_by_user
FROM public."track"
ORDER BY id
`

func (q *Queries) GetAllTracksForBackup(ctx context.Context) ([]Track, error) {
	rows, err := q.db.Query(ctx, getAllTracksForBackup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationMs,
			&i.Url,
			&i.FastPresetFname,
			&i.StandardPresetFname,
			&i.HighPresetFname,
			&i.LosslessPresetFname,
			&i.IsGloballyAvailable,
			&i.ArtistID,
			&i.UploadByUser,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTranscodingQueueForBackup = `-- name: GetAllTranscodingQueueForBackup :many
SELECT id, added_at, track_original_file_name, track_id, was_failed, error_msg
FROM public."transcoding_queue"
ORDER BY id
`

func (q *Queries) GetAllTranscodingQueueForBackup(ctx context.Context) ([]TranscodingQueue, error) {
	rows, err := q.db.Query(ctx, getAllTranscodingQueueForBackup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranscodingQueue
	for rows.Next() {
		var i TranscodingQueue
		if err := rows.Scan(
			&i.ID,
			&i.AddedAt,
			&i.TrackOriginalFileName,
			&i.TrackID,
			&i.WasFailed,
			&i.ErrorMsg,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsersForBackup = `-- name: GetAllUsersForBackup :many
SELECT id, username, is_superuser, email, password, salt, refresh_version, created_at, updated_at
FROM public."user"
ORDER BY id
`

func (q *Queries) GetAllUsersForBackup(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsersForBackup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.IsSuperuser,
			&i.Email,
			&i.Password,
			&i.Salt,
			&i.RefreshVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
