// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_by_track_id.sql

package db

import (
	"context"
)

const getAlbumByTrackID = `-- name: GetAlbumByTrackID :one
SELECT album_id FROM track_album
    WHERE track_id = $1
    LIMIT 1
`

func (q *Queries) GetAlbumByTrackID(ctx context.Context, trackID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getAlbumByTrackID, trackID)
	var album_id int32
	err := row.Scan(&album_id)
	return album_id, err
}
