// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_restore_status.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRestoreStatus = `-- name: GetRestoreStatus :one
SELECT id, status, error, created_at, finished_at
FROM public."restore_status"
    WHERE id = $1
`

type GetRestoreStatusRow struct {
	ID         string
	Status     Status
	Error      pgtype.Text
	CreatedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
}

func (q *Queries) GetRestoreStatus(ctx context.Context, id string) (GetRestoreStatusRow, error) {
	row := q.db.QueryRow(ctx, getRestoreStatus, id)
	var i GetRestoreStatusRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
