// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_all_filter.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArtistsWithFilter = `-- name: GetArtistsWithFilter :many
SELECT "id", "name" FROM artist
                    -- starts with
    WHERE "name" LIKE $1 || '%'
LIMIT $2
`

type GetArtistsWithFilterParams struct {
	Column1 pgtype.Text
	Limit   int32
}

func (q *Queries) GetArtistsWithFilter(ctx context.Context, arg GetArtistsWithFilterParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArtistsWithFilter, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
