// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_backup_status.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBackupStatus = `-- name: GetBackupStatus :one
SELECT id, status, error, created_at, finished_at,
    include_images, include_transcoded_tracks, archive_path, size_bytes
FROM public."backup_status"
WHERE id = $1
`

type GetBackupStatusRow struct {
	ID                      string
	Status                  Status
	Error                   pgtype.Text
	CreatedAt               pgtype.Timestamptz
	FinishedAt              pgtype.Timestamptz
	IncludeImages           bool
	IncludeTranscodedTracks bool
	ArchivePath             pgtype.Text
	SizeBytes               pgtype.Int8
}

func (q *Queries) GetBackupStatus(ctx context.Context, id string) (GetBackupStatusRow, error) {
	row := q.db.QueryRow(ctx, getBackupStatus, id)
	var i GetBackupStatusRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.IncludeImages,
		&i.IncludeTranscodedTracks,
		&i.ArchivePath,
		&i.SizeBytes,
	)
	return i, err
}
