// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mark_restore_operation_started.sql

package db

import (
	"context"
)

const markRestoreOperationStarted = `-- name: MarkRestoreOperationStarted :exec
UPDATE public."restore_status" SET
    status = 'started'
WHERE id = $1
`

func (q *Queries) MarkRestoreOperationStarted(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markRestoreOperationStarted, id)
	return err
}
