// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mark_backup_operation_started.sql

package db

import (
	"context"
)

const markBackupOperationStarted = `-- name: MarkBackupOperationStarted :exec
UPDATE public."backup_status" SET
    status = 'started'
WHERE id = $1
`

func (q *Queries) MarkBackupOperationStarted(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markBackupOperationStarted, id)
	return err
}
