// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID       int32
	Name     string
	ArtistID int32
}

type Artist struct {
	ID   int32
	Name string
}

type Playlist struct {
	ID      int32
	Name    string
	OwnerID pgtype.Int4
}

type Track struct {
	ID                  int32
	Name                string
	DurationMs          pgtype.Int4
	Url                 pgtype.Text
	FastPresetFname     pgtype.Text
	StandardPresetFname pgtype.Text
	HighPresetFname     pgtype.Text
	LosslessPresetFname pgtype.Text
	IsGloballyAvailable bool
	ArtistID            int32
	UploadByUser        pgtype.Int4
}

type TrackAlbum struct {
	TrackID int32
	AlbumID int32
}

type TrackPlaylist struct {
	TrackID    int32
	PlaylistID int32
}

type TranscodingQueue struct {
	ID                    int32
	AddedAt               pgtype.Timestamp
	TrackOriginalFileName string
	TrackID               int32
	WasFailed             bool
	ErrorMsg              pgtype.Text
}

type User struct {
	ID        int32
	Username  string
	Email     pgtype.Text
	Password  []byte
	Salt      []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
