// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type Status string

const (
	StatusPending  Status = "pending"
	StatusStarted  Status = "started"
	StatusFinished Status = "finished"
	StatusError    Status = "error"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type NullStatus struct {
	Status Status
	Valid  bool // Valid is true if Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatus) Scan(value interface{}) error {
	if value == nil {
		ns.Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Status), nil
}

type Album struct {
	ID              int32
	Name            string
	ReleaseYear     pgtype.Int4
	ReleaseFullDate pgtype.Date
	ArtistID        int32
}

type Artist struct {
	ID   int32
	Name string
	Url  pgtype.Text
}

type Playlist struct {
	ID       int32
	Name     string
	IsPublic bool
	OwnerID  pgtype.Int4
}

type RestoreStatus struct {
	ID         string
	CreatedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Status     Status
	Error      pgtype.Text
}

type Track struct {
	ID                  int32
	Name                string
	DurationMs          pgtype.Int4
	Url                 pgtype.Text
	FastPresetFname     pgtype.Text
	StandardPresetFname pgtype.Text
	HighPresetFname     pgtype.Text
	LosslessPresetFname pgtype.Text
	IsGloballyAvailable bool
	ArtistID            int32
	UploadByUser        pgtype.Int4
}

type TrackAlbum struct {
	TrackID int32
	AlbumID int32
}

type TrackPlaylist struct {
	TrackID    int32
	PlaylistID int32
}

type TranscodingQueue struct {
	ID                    int32
	AddedAt               pgtype.Timestamp
	TrackOriginalFileName string
	TrackID               int32
	WasFailed             bool
	ErrorMsg              pgtype.Text
}

type User struct {
	ID          int32
	Username    string
	IsSuperuser bool
	Email       pgtype.Text
	Password    []byte
	Salt        []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
