// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: num_users.sql

package db

import (
	"context"
)

const getUserCount = `-- name: GetUserCount :one
SELECT COUNT(*) FROM public."user"
`

func (q *Queries) GetUserCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getUserCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
