// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restore_album.sql

package db

import (
	"context"
)

const restoreAlbum = `-- name: RestoreAlbum :exec
INSERT INTO public."album" (
    id, name, artist_id
) VALUES (
    $1, $2, $3
)
`

type RestoreAlbumParams struct {
	ID       int32
	Name     string
	ArtistID int32
}

func (q *Queries) RestoreAlbum(ctx context.Context, arg RestoreAlbumParams) error {
	_, err := q.db.Exec(ctx, restoreAlbum, arg.ID, arg.Name, arg.ArtistID)
	return err
}
