// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restore_track.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const restoreTrack = `-- name: RestoreTrack :exec
INSERT INTO public."track" (
    id, name, duration_ms, url,
    fast_preset_fname, standard_preset_fname,
    high_preset_fname, lossless_preset_fname,
    is_globally_available, artist_id, upload_by_user
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11
)
`

type RestoreTrackParams struct {
	ID                  int32
	Name                string
	DurationMs          pgtype.Int4
	Url                 pgtype.Text
	FastPresetFname     pgtype.Text
	StandardPresetFname pgtype.Text
	HighPresetFname     pgtype.Text
	LosslessPresetFname pgtype.Text
	IsGloballyAvailable bool
	ArtistID            int32
	UploadByUser        pgtype.Int4
}

func (q *Queries) RestoreTrack(ctx context.Context, arg RestoreTrackParams) error {
	_, err := q.db.Exec(ctx, restoreTrack,
		arg.ID,
		arg.Name,
		arg.DurationMs,
		arg.Url,
		arg.FastPresetFname,
		arg.StandardPresetFname,
		arg.HighPresetFname,
		arg.LosslessPresetFname,
		arg.IsGloballyAvailable,
		arg.ArtistID,
		arg.UploadByUser,
	)
	return err
}
