// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restore_track_playlist.sql

package db

import (
	"context"
)

const restoreTrackPlaylist = `-- name: RestoreTrackPlaylist :exec
INSERT INTO public."track_playlist" (
    track_id, playlist_id
) VALUES (
    $1, $2
)
`

type RestoreTrackPlaylistParams struct {
	TrackID    int32
	PlaylistID int32
}

func (q *Queries) RestoreTrackPlaylist(ctx context.Context, arg RestoreTrackPlaylistParams) error {
	_, err := q.db.Exec(ctx, restoreTrackPlaylist, arg.TrackID, arg.PlaylistID)
	return err
}
