// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restore_track_album.sql

package db

import (
	"context"
)

const restoreTrackAlbum = `-- name: RestoreTrackAlbum :exec
INSERT INTO public."track_album" (
    track_id, album_id
) VALUES (
    $1, $2
)
`

type RestoreTrackAlbumParams struct {
	TrackID int32
	AlbumID int32
}

func (q *Queries) RestoreTrackAlbum(ctx context.Context, arg RestoreTrackAlbumParams) error {
	_, err := q.db.Exec(ctx, restoreTrackAlbum, arg.TrackID, arg.AlbumID)
	return err
}
