// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restore_transcoding_queue.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const restoreTranscodingQueue = `-- name: RestoreTranscodingQueue :exec
INSERT INTO public."transcoding_queue" (
    id, added_at, track_original_file_name,
    track_id, was_failed, error_msg
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type RestoreTranscodingQueueParams struct {
	ID                    int64
	AddedAt               pgtype.Timestamp
	TrackOriginalFileName string
	TrackID               int32
	WasFailed             bool
	ErrorMsg              pgtype.Text
}

func (q *Queries) RestoreTranscodingQueue(ctx context.Context, arg RestoreTranscodingQueueParams) error {
	_, err := q.db.Exec(ctx, restoreTranscodingQueue,
		arg.ID,
		arg.AddedAt,
		arg.TrackOriginalFileName,
		arg.TrackID,
		arg.WasFailed,
		arg.ErrorMsg,
	)
	return err
}
