// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restore_playlist.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const restorePlaylist = `-- name: RestorePlaylist :exec
INSERT INTO public."playlist" (
    id, name, is_public, owner_id
) VALUES (
    $1, $2, $3, $4
)
`

type RestorePlaylistParams struct {
	ID       int32
	Name     string
	IsPublic bool
	OwnerID  pgtype.Int4
}

func (q *Queries) RestorePlaylist(ctx context.Context, arg RestorePlaylistParams) error {
	_, err := q.db.Exec(ctx, restorePlaylist,
		arg.ID,
		arg.Name,
		arg.IsPublic,
		arg.OwnerID,
	)
	return err
}
