// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restore_artist.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const restoreArtist = `-- name: RestoreArtist :exec
INSERT INTO public."artist" (
    id, name, url
) VALUES (
    $1, $2, $3
)
`

type RestoreArtistParams struct {
	ID   int32
	Name string
	Url  pgtype.Text
}

func (q *Queries) RestoreArtist(ctx context.Context, arg RestoreArtistParams) error {
	_, err := q.db.Exec(ctx, restoreArtist, arg.ID, arg.Name, arg.Url)
	return err
}
