// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restore_playlist_share_info.sql

package db

import (
	"context"
)

const restorePlaylistShareInfo = `-- name: RestorePlaylistShareInfo :exec
INSERT INTO public."playlist_share_info" (
    playlist_id, shared_with_user, has_write_permission
) VALUES (
    $1, $2, $3
)
`

type RestorePlaylistShareInfoParams struct {
	PlaylistID         int32
	SharedWithUser     int32
	HasWritePermission bool
}

func (q *Queries) RestorePlaylistShareInfo(ctx context.Context, arg RestorePlaylistShareInfoParams) error {
	_, err := q.db.Exec(ctx, restorePlaylistShareInfo, arg.PlaylistID, arg.SharedWithUser, arg.HasWritePermission)
	return err
}
