// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restore_user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const restoreUser = `-- name: RestoreUser :exec
INSERT INTO public."user" (
    id, username, is_superuser, email,
    password, salt, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
`

type RestoreUserParams struct {
	ID          int32
	Username    string
	IsSuperuser bool
	Email       pgtype.Text
	Password    []byte
	Salt        []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) RestoreUser(ctx context.Context, arg RestoreUserParams) error {
	_, err := q.db.Exec(ctx, restoreUser,
		arg.ID,
		arg.Username,
		arg.IsSuperuser,
		arg.Email,
		arg.Password,
		arg.Salt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
