// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_artists.sql

package db

import (
	"context"
)

const searchArtists = `-- name: SearchArtists :many
SELECT 
    ar.id as artist_id,
    ar.name as artist_name,
    similarity(ar.name, $1) as score
FROM "artist" ar
WHERE ar.name ILIKE '%' || $1::text || '%'
    OR ar.name % $1::text
ORDER BY
    lower(ar.name) = lower($1::text) DESC,
    lower(ar.name) ILIKE lower($1::text) || '%' DESC,
    score DESC,
    ar.name
LIMIT $2::integer
`

type SearchArtistsParams struct {
	Query string
	Bound int32
}

type SearchArtistsRow struct {
	ArtistID   int32
	ArtistName string
	Score      float32
}

func (q *Queries) SearchArtists(ctx context.Context, arg SearchArtistsParams) ([]SearchArtistsRow, error) {
	rows, err := q.db.Query(ctx, searchArtists, arg.Query, arg.Bound)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchArtistsRow
	for rows.Next() {
		var i SearchArtistsRow
		if err := rows.Scan(&i.ArtistID, &i.ArtistName, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
