// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_albums.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchAlbums = `-- name: SearchAlbums :many
SELECT 
    al.id as album_id,
    al.name as name,
    al.artist_id as artist_id,
    ar.name as artist_name,
    al.release_year as release_year,
    similarity(al.name, $1) as score
FROM "album" al
INNER JOIN "artist" ar ON al.artist_id = ar.id
WHERE al.name ILIKE '%' || $1::text || '%'
    OR al.name % $1::text
ORDER BY
    lower(al.name) = lower($1::text) DESC,
    lower(al.name) ILIKE lower($1::text) || '%' DESC,
    score DESC,
    al.name
LIMIT $2::integer
`

type SearchAlbumsParams struct {
	Query string
	Bound int32
}

type SearchAlbumsRow struct {
	AlbumID     int32
	Name        string
	ArtistID    int32
	ArtistName  string
	ReleaseYear pgtype.Int4
	Score       float32
}

func (q *Queries) SearchAlbums(ctx context.Context, arg SearchAlbumsParams) ([]SearchAlbumsRow, error) {
	rows, err := q.db.Query(ctx, searchAlbums, arg.Query, arg.Bound)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchAlbumsRow
	for rows.Next() {
		var i SearchAlbumsRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.Name,
			&i.ArtistID,
			&i.ArtistName,
			&i.ReleaseYear,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
