// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search_tracks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const searchTracks = `-- name: SearchTracks :many
SELECT
    t.id,
    t.name,
    t.artist_id,
    ar.name AS artist_name,
    al.id AS album_id,
    al.name AS album_name,
    t.duration_ms,
    t.is_globally_available,
    GREATEST(
        similarity(t.name, $1),
        similarity(ar.name, $1),
        similarity(al.name, $1)
    )::real AS score
FROM track t
JOIN artist ar ON ar.id = t.artist_id
JOIN track_album ta ON ta.track_id = t.id
JOIN album al ON al.id = ta.album_id
WHERE
    (
        t.name ILIKE '%' || $1::text || '%'
        OR ar.name ILIKE '%' || $1::text || '%'
        OR al.name ILIKE '%' || $1::text || '%'
        OR t.name % $1::text
        OR ar.name % $1::text
        OR al.name % $1::text
    )
    AND ( -- track is available to user
        t.is_globally_available
        OR t.upload_by_user = $2::integer
        OR EXISTS (
            SELECT 1
            FROM track_playlist tp
            INNER JOIN playlist p ON p.id = tp.playlist_id
            LEFT JOIN playlist_share_info psi
                ON psi.playlist_id = p.id
                AND psi.shared_with_user = $2::integer
            WHERE tp.track_id = t.id
                AND (
                    p.owner_id = $2::integer
                    OR p.is_public IS TRUE
                    OR psi.shared_with_user IS NOT NULL
                ))
    )
ORDER BY
    lower(t.name) = lower($1::text) DESC,
    lower(t.name) ILIKE lower($1::text) || '%' DESC,
    score DESC,
    t.name
LIMIT $3::integer
`

type SearchTracksParams struct {
	Query  string
	UserID int32
	Bound  int32
}

type SearchTracksRow struct {
	ID                  int32
	Name                string
	ArtistID            int32
	ArtistName          string
	AlbumID             int32
	AlbumName           string
	DurationMs          pgtype.Int4
	IsGloballyAvailable bool
	Score               float32
}

func (q *Queries) SearchTracks(ctx context.Context, arg SearchTracksParams) ([]SearchTracksRow, error) {
	rows, err := q.db.Query(ctx, searchTracks, arg.Query, arg.UserID, arg.Bound)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTracksRow
	for rows.Next() {
		var i SearchTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ArtistID,
			&i.ArtistName,
			&i.AlbumID,
			&i.AlbumName,
			&i.DurationMs,
			&i.IsGloballyAvailable,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
