// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: share.sql

package db

import (
	"context"
)

const sharePlaylistWith = `-- name: SharePlaylistWith :exec
INSERT INTO "playlist_share_info"
    (playlist_id, shared_with_user, has_write_permission)
    VALUES ($1, $2, $3)
`

type SharePlaylistWithParams struct {
	PlaylistID         int32
	SharedWithUser     int32
	HasWritePermission bool
}

func (q *Queries) SharePlaylistWith(ctx context.Context, arg SharePlaylistWithParams) error {
	_, err := q.db.Exec(ctx, sharePlaylistWith, arg.PlaylistID, arg.SharedWithUser, arg.HasWritePermission)
	return err
}
