// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: start_backup.sql

package db

import (
	"context"
)

const startBackupOperation = `-- name: StartBackupOperation :one
INSERT INTO public."backup_status" (
    id, status, include_images, include_transcoded_tracks
) VALUES (
    $1, 'pending', $2, $3
)
RETURNING id
`

type StartBackupOperationParams struct {
	ID                      string
	IncludeImages           bool
	IncludeTranscodedTracks bool
}

func (q *Queries) StartBackupOperation(ctx context.Context, arg StartBackupOperationParams) (string, error) {
	row := q.db.QueryRow(ctx, startBackupOperation, arg.ID, arg.IncludeImages, arg.IncludeTranscodedTracks)
	var id string
	err := row.Scan(&id)
	return id, err
}
