// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: start_restoring.sql

package db

import (
	"context"
)

const startRestoreOperation = `-- name: StartRestoreOperation :one
INSERT INTO public."restore_status" (id, status)
    VALUES ($1, 'started')
    RETURNING id
`

func (q *Queries) StartRestoreOperation(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, startRestoreOperation, id)
	err := row.Scan(&id)
	return id, err
}
