// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_backup_sequences.sql

package db

import (
	"context"
)

const syncAlbumSequence = `-- name: SyncAlbumSequence :one
SELECT setval(
    pg_get_serial_sequence('public.album', 'id'),
    GREATEST(COALESCE(MAX(id), 0), 1),
    COALESCE(MAX(id), 0) > 0
)
FROM public."album"
`

func (q *Queries) SyncAlbumSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, syncAlbumSequence)
	var setval int64
	err := row.Scan(&setval)
	return setval, err
}

const syncArtistSequence = `-- name: SyncArtistSequence :one
SELECT setval(
    pg_get_serial_sequence('public.artist', 'id'),
    GREATEST(COALESCE(MAX(id), 0), 1),
    COALESCE(MAX(id), 0) > 0
)
FROM public."artist"
`

func (q *Queries) SyncArtistSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, syncArtistSequence)
	var setval int64
	err := row.Scan(&setval)
	return setval, err
}

const syncPlaylistSequence = `-- name: SyncPlaylistSequence :one
SELECT setval(
    pg_get_serial_sequence('public.playlist', 'id'),
    GREATEST(COALESCE(MAX(id), 0), 1),
    COALESCE(MAX(id), 0) > 0
)
FROM public."playlist"
`

func (q *Queries) SyncPlaylistSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, syncPlaylistSequence)
	var setval int64
	err := row.Scan(&setval)
	return setval, err
}

const syncTrackSequence = `-- name: SyncTrackSequence :one
SELECT setval(
    pg_get_serial_sequence('public.track', 'id'),
    GREATEST(COALESCE(MAX(id), 0), 1),
    COALESCE(MAX(id), 0) > 0
)
FROM public."track"
`

func (q *Queries) SyncTrackSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, syncTrackSequence)
	var setval int64
	err := row.Scan(&setval)
	return setval, err
}

const syncTranscodingQueueSequence = `-- name: SyncTranscodingQueueSequence :one
SELECT setval(
    pg_get_serial_sequence('public.transcoding_queue', 'id'),
    GREATEST(COALESCE(MAX(id), 0), 1),
    COALESCE(MAX(id), 0) > 0
)
FROM public."transcoding_queue"
`

func (q *Queries) SyncTranscodingQueueSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, syncTranscodingQueueSequence)
	var setval int64
	err := row.Scan(&setval)
	return setval, err
}

const syncUserSequence = `-- name: SyncUserSequence :one
SELECT setval(
    pg_get_serial_sequence('public."user"', 'id'),
    GREATEST(COALESCE(MAX(id), 0), 1),
    COALESCE(MAX(id), 0) > 0
)
FROM public."user"
`

func (q *Queries) SyncUserSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, syncUserSequence)
	var setval int64
	err := row.Scan(&setval)
	return setval, err
}
