// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_password_reset_code_attempts.sql

package db

import (
	"context"
)

const updatePasswordResetCodeAttempts = `-- name: UpdatePasswordResetCodeAttempts :exec
UPDATE "password_reset_code" SET
    attempts_left = $2,
    updated_at = now()
WHERE user_id = $1
`

type UpdatePasswordResetCodeAttemptsParams struct {
	UserID       int32
	AttemptsLeft int32
}

func (q *Queries) UpdatePasswordResetCodeAttempts(ctx context.Context, arg UpdatePasswordResetCodeAttemptsParams) error {
	_, err := q.db.Exec(ctx, updatePasswordResetCodeAttempts, arg.UserID, arg.AttemptsLeft)
	return err
}
