// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user_password_hash_params.sql

package db

import (
	"context"
)

const updateUserPasswordHashParams = `-- name: UpdateUserPasswordHashParams :exec
UPDATE "user" SET
    password_memory = $2,
    password_iterations = $3,
    password_parallelism = $4,
    password_key_length = $5,
    updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordHashParamsParams struct {
	ID                  int32
	PasswordMemory      int32
	PasswordIterations  int32
	PasswordParallelism int32
	PasswordKeyLength   int32
}

func (q *Queries) UpdateUserPasswordHashParams(ctx context.Context, arg UpdateUserPasswordHashParamsParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHashParams,
		arg.ID,
		arg.PasswordMemory,
		arg.PasswordIterations,
		arg.PasswordParallelism,
		arg.PasswordKeyLength,
	)
	return err
}
