// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update.sql

package db

import (
	"context"
)

const updatePlaylist = `-- name: UpdatePlaylist :one
UPDATE public."playlist" SET
    name = $2
WHERE id = $1
RETURNING id, name, is_public, owner_id
`

type UpdatePlaylistParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, updatePlaylist, arg.ID, arg.Name)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPublic,
		&i.OwnerID,
	)
	return i, err
}
