// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_album.sql

package db

import (
	"context"
)

const replaceTrackAlbum = `-- name: ReplaceTrackAlbum :exec
WITH deleted AS (
    DELETE FROM "track_album"
    WHERE track_id = $1::integer
)
INSERT INTO "track_album" (track_id, album_id)
VALUES ($1::integer, $2::integer)
`

type ReplaceTrackAlbumParams struct {
	TrackID int32
	AlbumID int32
}

func (q *Queries) ReplaceTrackAlbum(ctx context.Context, arg ReplaceTrackAlbumParams) error {
	_, err := q.db.Exec(ctx, replaceTrackAlbum, arg.TrackID, arg.AlbumID)
	return err
}
