// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_user_password.sql

package db

import (
	"context"
)

const updateUserPassword = `-- name: UpdateUserPassword :exec
WITH updated_user AS (
    UPDATE "user" SET
        password = $2,
        salt = $3,
        password_memory = $4,
        password_iterations = $5,
        password_parallelism = $6,
        password_key_length = $7,
        refresh_version = refresh_version + 1,
        updated_at = now()
    WHERE id = $1
    RETURNING id
)
DELETE FROM "password_reset_code"
WHERE user_id IN (SELECT id FROM updated_user)
`

type UpdateUserPasswordParams struct {
	ID                  int32
	Password            []byte
	Salt                []byte
	PasswordMemory      int32
	PasswordIterations  int32
	PasswordParallelism int32
	PasswordKeyLength   int32
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword,
		arg.ID,
		arg.Password,
		arg.Salt,
		arg.PasswordMemory,
		arg.PasswordIterations,
		arg.PasswordParallelism,
		arg.PasswordKeyLength,
	)
	return err
}
