// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: update_to_superuser.sql

package db

import (
	"context"
)

const updateToSuperuser = `-- name: UpdateToSuperuser :one
UPDATE public."user" SET
    is_superuser = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, username, is_superuser, email, password, salt, created_at, updated_at
`

type UpdateToSuperuserParams struct {
	ID          int32
	IsSuperuser bool
}

func (q *Queries) UpdateToSuperuser(ctx context.Context, arg UpdateToSuperuserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateToSuperuser, arg.ID, arg.IsSuperuser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IsSuperuser,
		&i.Email,
		&i.Password,
		&i.Salt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
