// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upsert_password_reset_code.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertPasswordResetCode = `-- name: UpsertPasswordResetCode :exec
INSERT INTO "password_reset_code" (
    user_id, code_hash, expires_at, attempts_left,
    resend_available_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4,
    $5, now(), now()
)
ON CONFLICT (user_id) DO UPDATE SET
    code_hash = EXCLUDED.code_hash,
    expires_at = EXCLUDED.expires_at,
    attempts_left = EXCLUDED.attempts_left,
    resend_available_at = EXCLUDED.resend_available_at,
    created_at = EXCLUDED.created_at,
    updated_at = now()
`

type UpsertPasswordResetCodeParams struct {
	UserID            int32
	CodeHash          []byte
	ExpiresAt         pgtype.Timestamptz
	AttemptsLeft      int32
	ResendAvailableAt pgtype.Timestamptz
}

func (q *Queries) UpsertPasswordResetCode(ctx context.Context, arg UpsertPasswordResetCodeParams) error {
	_, err := q.db.Exec(ctx, upsertPasswordResetCode,
		arg.UserID,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.AttemptsLeft,
		arg.ResendAvailableAt,
	)
	return err
}
